### ISSUE TITLE
Error when people remove their friends

### ISSUE THREAD

**Issue by happycoder1337** [SocialEngine/phpv4-issues#220] opened 2015-08-03 19:38 UTC
This is the error message I got from social engine log:

WARN (4): [2] Creating default object from empty value (/application/modules/User/Model/DbTable/Lists.php) [29]

Fresh SE 4.8.9

**Comment by happycoder1337** [comment] 2015-08-04 16:08
SE 4 has been around for years now, and only now Webligo decides to track bugs. look how many bugs there is on SE. WOW. no wonder why communities are dying.

**Comment by shivani2910** [comment] 2015-08-05 10:22
@happycoder1337 We've checked this issue in default installation at our end but unable to reproduce this in our error logs. Also, this doesn't seem to be a known issue in latest version.

Since the issue is being faced on your specific installation, I suggest you opening a support ticket for this so that our support team can look deeper into the problem on your server. Thanks.

**Comment by happycoder1337** [comment] 2015-08-05 17:24
I just reinstalled a new SE 4 and tested. the same.

2015-08-05T17:22:10+00:00 WARN (4): [2] Creating default object from empty value (/application/modules/User/Model/DbTable/Lists.php) [29]
Error Code: 5f85fc
Stack trace:
#0 (unknown file)(0): User_Model_DbTable_Lists->removeFriendFromLists(User_Model_User, User_Model_User)
#1 /application/libraries/Engine/ProxyObject.php(65): ReflectionMethod->invokeArgs(User_Model_DbTable_Lists, Array)
#2 /application/modules/User/controllers/FriendsController.php(674): Engine_ProxyObject->__call('removeFriendFromLists', Array)
#3 /application/modules/User/controllers/FriendsController.php(674): Engine_ProxyObject->removeFriendFromLists(User_Model_User)
#4 /application/libraries/Zend/Controller/Action.php(516): User_FriendsController->removeAction()
#5 /application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('removeAction')
#6 /application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Zend_Controller_Request_Http, Zend_Controller_Response_Http)
#7 /application/modules/Core/Bootstrap.php(87): Zend_Controller_Front->dispatch()
#8 /application/libraries/Engine/Application.php(160): Core_Bootstrap->run()
#9 /application/index.php(214): Engine_Application->run()
#10 /index.php(24): include(‘/…’)
#11 {main}

**Comment by smazurov** [comment] 2015-08-05 20:56
please provide reproduction steps.

**Comment by happycoder1337** [comment] 2015-08-05 23:11
Add someone as friend, after confirmation, remove friendship. These errors appears on fresh install of 4.8.9.

**Comment by Elshara** [comment] 2015-08-09 21:29
Confirmed error on my end also.

**Comment by Anshuse** [comment] 2015-08-10 12:34
Hi @happycoder1337 , thanks for providing the steps to reproduce this error log at our end. We're able to reproduce this error log at end and we're reporting this at our end to resolve this in near future release. Thanks!

**Comment by smazurov** [comment] 2016-01-20 21:27
Fixed in [4.8.10](http://blog.socialengine.com/2016/01/20/socialengine-php-4-8-10-is-released/)

**Closed by smazurov** 2016-01-20 21:27 UTC
Labels: bug
