### ISSUE TITLE
BUG - Reoccurring Subscriptions never charges user 

### ISSUE THREAD

**Issue by dreamgeekcoder** [SocialEngine/phpv4-issues#629] opened 2017-03-30 20:38 UTC
I've reported this all over the place but will report here again. 

There is a bug with reoccurring Paypal subscriptions. If ANYONE ELSE has reoccurring paypal subscriptions please comment here.  I'd seriously appreciate it so Social Engine takes me seriously instead of saying this is MY site issue. 

Steps to replicate the issue. 

1) Set up a monthly reoccurring Upgraded membership level on SE Site. Check *Wait until the gateway signals that the payment has completed successfully.* under /admin/payment/settings
2) User signs up on paid subscription option with Paypal
3) The user and site owner get an email from Paypal AND the site saying a profile has been created ( You have a new automatic payment profile for ..... ) even though no actual payment has happened yet.
4) The user is immediately upgraded to the paid level on the SE site even though they have not paid anything.
5) The user is then charged at a later point in the next 24 hours

If it goes like that everything is mostly fine although they were upgraded before the actual payment happened, but that wouldnt be a huge issue.

**_Where this becomes an issue_** is that the User does not have the funds in the paypal account to complete the transaction in that 24 hour period. Then what happens?

6)Paypal sends back an error to the site admin and an email that says (Payment skipped) and "will try again" for infinity. The user is not notified. You never get your money. Paypal keeps trying every couple of days to get it. The user is then free to cancel their account at any time. Because of this [https://github.com/SocialEngine/phpv4-issues/issues/537](https://github.com/SocialEngine/phpv4-issues/issues/537) issue i previously reported. A user can create an account, never pay, be upgraded, cancel and be free again without ever paying anything. Subscriptions on SE is basically useless with this bug.

IPN PAYPAL LOGS

PROFILEID=I%2dJKNKGAXXXX&PROFILESTATUS=**ActiveProfile**&TIMESTAMP=2017%2d03%2d22T16%3a11%3a59Z&CORRELATIONID=79dcd0XXXXXXXX&ACK=Success&VERSION=65%2e0&BUILD=252XXXX

2017-03-22T12:11:59-04:00 INFO (6): CreateRecurringPaymentsProfile: Array
(
[PROFILEID] => I-JKNXXXXXXXX
[PROFILESTATUS] => **ActiveProfile**
[TIMESTAMP] => 2017-03-22T16:11:59Z
[CORRELATIONID] => 79dcd0XXXXX
[ACK] => Success
[VERSION] => 65.0
[BUILD] => 252XXXX
)

2017-03-22T12:12:03-04:00: Array
(
[payment_cycle] => Monthly
[txn_type] => recurring_payment_profile_created
[last_name] => Smith
[next_payment_date] => 03:00:00 Mar 22, 2017 PDT
[residence_country] => CA
[initial_payment_amount] => 0.00
[rp_invoice_id] => 571
[currency_code] => USD
[time_created] => 09:11:58 Mar 22, 2017 PDT
[verify_sign] => ATldzfYZWnKdK0zkRl1nRve1Ig3mAhII0OOEb5QjHIIkVyXXXXXXXXX
[period_type] => Regular
[payer_status] => verified
[tax] => 0.00
[payer_email] => XXX@XXX.com
[first_name] => Bob
[receiver_email] => xxxxxx@XXXXXX.com
[payer_id] => VMED7RXXXXXX
[product_type] => 1
[shipping] => 0.00
[amount_per_cycle] => 9.99
**[profile_status] => Active**
[charset] => windows-1252
[notify_version] => 3.8
[amount] => 9.99
[outstanding_balance] => 0.00
[recurring_payment_id] => I-JXXXXXXXXX
[product_name] => $9.99 monthly
[ipn_track_id] => 79dcd0286XXXX
[gatewayType] => PayPal
)

The paypal IPN logs never ever show a pending, temp, hold transaction ever... only Active so the user is immediately made active, EVERY time. Regardless of previous transactions or not. 

OVERALL POINT
The user is getting the upgraded options and is not reporting it - infact may not even be aware they haven't actually paid because they got the email saying the account had been created. Unless you had enough transactions happening where users did not have enough money in the account to cover it - this bug would not show up or be noticed.

So please, as I've argued this many times with support and the development team here, none of which will take responsibility for it - If YOU have paypal subscriptions on your site can you PLEASE tell me if you have noticed this bug or if you have pending, held, hold etc in any of you Paypal IPN logs.

Thank you.

**Comment by Elshara** [comment] 2017-03-31 04:48
What I started doing back when I was running pay pal integration was
recording the user ID and email of who ever was automatically versus
manually being transferred over to paid membership level. I'd
automatically ensure they paid and I had a record of it otherwise I'd
just reverse their membership. But even if I did that and canceled
their pay pal subscription, they'd still be getting charged monthly.
People were able to automatically recur their subscriptions but the
bug I found was that their subscription in pay pal would remain the
same, even if they chose another package in social engine.
So yeah I can confirm social engine and pay pal aren't communicating
very well through the API pay pal set up. It's extremely annoying and
inefficient.
1. Social Engine communicates to pay pal someone wants to pay a
specific pay pal account a certain amount.
Then won't adjust subscription regardless of what a member tries to do
to escape it.
They have to go into pay pal and manually disconnect their
subscription from paying the specific account. And then usually would
charge for refunds.
2. Social Engine doesn't stop trying to processed failed or reverse
payments. Pay pal keeps trying to pay where there are no funds
available. There's no way to block payments in pay pal if the money
doesn't go through, because of how the integration with their API
works with social engine. Therefore, requiring manual intervention.
3. Such activity over time, doesn't guarantee safe transfers because
social engine does not provide secure HTTPS validation for payment
details to go through when handing over transaction details to pay
pal.
I could go on. But what I ended up doing, is just providing a button
for people to click in order to make a donation or recurring amount of
money to the site itself. This way, people know what they're getting
into, it works, and if anyone doesn't have the ability to access pay
pal in their country, they can always write to the address on the
donation page itself.
I usually manually approve accounts which do donate to special paid
membership level anyways and assign such duties personally, actually
making myself known to anyone who does pay, in a personal way.
Explaining they are appreciated and valued for providing such a
flexible contribution to the site.
Does it mean anything? Sure. People love it. They just don't like not
being able to be able to afford something they think won't be put to
good use if such were to happen.
How successful is it? That depends on your enforcement of where the
ability is pressed. If people want something, you have to show them a
way to get it so they feel comfortable with the means, the method and
are aware of what they are doing without regret, while being
interested enough to want to throw money at it. And the buggy nature
of how social engine deals with modern applications, is proof this
process is faulty and has to change. You aren't alone in this request.
I dare say the entire back end structure of social engine needs a huge revamp.

**Comment by dreamgeekcoder** [comment] 2017-03-31 05:29
Thanks for commenting @Elshara ... I have hundreds of paypal transactions happening on my site a month. There is no way I can personally monitor them in the level you are describing, nor should we have to. :)

> 2. Social Engine doesn't stop trying to processed failed or reverse
> payments. Pay pal keeps trying to pay where there are no funds
> available.  

This is an issue because there is no failed attempt coded in. It should fail after 3 times and suspend the user. This of course is missing but I'm trying to focus on the MAIN issue of a user is upgraded without paying.

Looking for input from ANYONE else who is doing subscriptions.  :)

**Comment by DonnaScriptTechs** [comment] 2017-03-31 14:57
Hi @dreamgeekcoder ,
I see you are submitting this issue again after we closed the other one. I'm just following up as I see that we have one issue in our list to fix and the other to look at. I've asked for some info for this so our team can know if we need to close this as a duplicate and re-open the other report to update you on that progress. As soon as I get any info from our team, I'll update you or another team member will, perhaps one of our developers. 

I am not a developer, I'm the Chief Evangelist for SocialEngine. Please also feel free to contact me at our community if you need personal attention from me https://community.onsocialengine.com/profile/231316 . You can access our community from your account at https://www.socialengine.com/

Thank you for your time and attention to this. We apologize that you had to submit it twice.

**Comment by dreamgeekcoder** [comment] 2017-03-31 18:41
Hi @donnab 

Yes there is lots of back and forth. Support said I'd need to pay. Development said no one else had reported the issue so it's not an  issue.

I am not paying for extending support when this is a bug, regardless of no one else submitting it. I was actually pretty shocked I've heard 'no one else reported it so it's not a bug' from multiple people at social engine.

Isn't that exactly what this forum is for? Reporting bugs social engine team has not found.

Thanks for following up.

**Comment by Elshara** [comment] 2017-03-31 19:30
That's exactly what this forum is for. It's just the minority
ignorance approach to issues, seem to be taken if a new issue has not
been encountered before, tends to go through several stages.
1. How serious is it?
2. Can it be duplicated?
3. What type of purpose will it serve to fix it based on common network needs?
4. How much is the demand for a fix?
5. Will it benefit all clients if a core change was to be implemented?
I can see it all now. I don't recall reading the previous issue so I
figure since this one is newer just keep this one open and hopefully
another person using paid access can be of better help.
I'm sorry I wasn't of better help. If you rely on the ecommerce
features so much of the payment plugin, have you tried advanced
payment gateway functionality from a third party provider? Perhaps if
the code was fixed in one of those modules, they usually provide for
free, they could lend the bug fix to social engine team.

**Comment by donnab** [comment] 2017-03-31 19:33
I think you have the wrong addressee.


Donna Bloomquist, RN
Clinical Informatics
[cid:image001.png@01D2AA34.24FBAAA0]


715 Falconer Street
Jamestown, New York 14701

  E-mail:donnab@lutheran-jamestown.org<mailto:donnab@lutheran-jamestown.org>
'  Telephone: (716) 665-4905
'  Direct: (716) 665-8123
(    Mobile: (716) 490-4752
"  Web: www.lutheran-jamestown.org<http://www.lutheran-jamestown.org/>

**Comment by Elshara** [comment] 2017-03-31 22:51
That's the problem with git hub. You can mention anyone. I think it was a typo.

**Comment by DonnaScriptTechs** [comment] 2017-07-03 18:12
We've added this to our list to fix and scheduled it for 4.9.3. As this tracker is closing, we'll close this now. For new bugs, please post at our [new community](https://community.socialengine.com/forums/).

**Closed by DonnaScriptTechs** 2017-07-03 18:12 UTC
Labels: Bug
