### ISSUE TITLE
Updating Php to 7/7.1

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#670] opened 2017-04-15 00:01 UTC
SE 4.9
We updated the php from 5(something) to the 7.1 which social engine says it supports

(I have another website using 7.1 just fine in comparison) when we flick it on and wait, my website will not come up period..., Yet if we flip it back to 5(something) it comes right back up.... I tried both 7.0 and 7.1 and got the same issue, website refused to come back up until we flipped it back to what it was originally set to.

in-case it matters we are using Plesk.

**Comment by DonnaScriptTechs** [comment] 2017-04-15 08:51
Perhaps there are some setting conflicts? Our requirements page has some extra recommendations in it (not changed in this version) that might need to be checked. http://support.socialengine.com/php/customer/portal/articles/1649350-socialengine-requirements

Our demo runs PHP 7.1.3 without issue.
<img width="677" alt="demo7 1" src="https://cloud.githubusercontent.com/assets/6908282/25062240/f340204c-2196-11e7-85c4-7611de406da8.png">

**Comment by Elshara** [comment] 2017-04-15 18:37
Damn. I wish cloud Linux supported 7.1.3.
Here's hoping it works for others.

**Comment by SpiritWolfie** [comment] 2017-04-15 22:59
Leaving this open, just to be safe, will close it if I find out its on our end, but as far as can tell our configurations match up with the requirements based on what my server tech gave me... will go over it 'again' and again just to confirm

I've put a support ticket in asking them to confirm our loaded modules list.

**Comment by poeticjustice** [comment] 2017-04-15 23:18
@DonnaScriptTechs whats benifits for SE , by updating to php7 over 5.6?

**Comment by Elshara** [comment] 2017-04-16 05:42
Honestly, nothing apart from a newer php version number that took 3
years or so to make. More deprecated stuff from previous versions.

**Comment by gsf00001** [comment] 2017-04-16 15:50
==>"...nothing apart from a newer php version number..."

I'm hoping there's more to it than that, especially some decrease in page load times since 7.x should be much faster than 5.x, but I haven't updated to 4.9 yet to test this.  SE being as heavy a script as it is should hopefully benefit tremendously from the performance (for lack of a better word) of PHP7.x.  Fingers crossed ...

**Comment by Elshara** [comment] 2017-04-16 19:12
To be honest, the fewer php extensions you have installed, the faster
your site is.

**Comment by shivani2910** [comment] 2017-04-17 10:42
> whats benifits for SE , by updating to php7 over 5.6?

@poeticjustice PHP 7 has got many benefits and performance improvements over PHp 5.6. Here is all you need to know about those improvements:
https://blog.appdynamics.com/engineering/everything-you-need-to-know-about-php-7/
http://www.hongkiat.com/blog/php7/

Hope that helps!

**Comment by Elshara** [comment] 2017-04-17 17:28
:)

**Comment by GabryNet** [comment] 2017-04-21 05:21
Hello @Elshara , i can see from a lot of topics in here and other forums that when we post a problem with 4.9 if there is no way to test it in SE official demo we are sent to check our VPS if it fits SEPhp ... can you please post here your EasyApache4 compile so we can follow it and talk about the right extensions to enable or disable ? I think in this way we can take out from the discussion if is the server fault and we can consider that the problem comes from the SEPhp script ... hope you understand me , thank you !

**Comment by SpiritWolfie** [comment] 2017-04-21 05:29
@GabryNet 
Um... Your aware its me who's having this issue right...? As i'm the one who created this bug, and as far as my testing and confirmation from Ray that the modules we had enabled where the right ones, I am safely assuming its a issue with Social engine and not my boxes (unlikely I'd have this issue on 3 different boxes, including completely different oses etc...) yet I can still reproduce this. (Still can)

**Comment by GabryNet** [comment] 2017-04-21 07:21
@SpiritWolfie 
Yes yes i know you are the owner of the post but i have seen @Elshara mention that fewer php extensions you have installed, the faster your site is so i assume that he has some ideas about how to compile the corect EasyApache4 , i will like all of us to share an idea about what to use on our VPS to be 100% compatible with SE. I can see a lot of companies taking advantage of this new release to make money saying that for some dollars they can setup the server , but i think 90% of us we know how to setup, the only problem is that we don;t know exactly what to enable or not beside the default requirements for SE.
Thank you for your reply !

**Comment by GabryNet** [comment] 2017-04-21 07:28
For example this is my EasyApache4 profile

Current Profile

The currently installed packages on the server.
**Apache 2.4**

config

config-runtime

mod_bwlimited

mod_cache

mod_cgi

mod_deflate

mod_expires

mod_headers

mod_mime_magic

mod_mpm_prefork

mod_proxy

mod_proxy_fcgi

mod_proxy_http

mod_ruid2

mod_ssl

tools


**PHP 5.6**

libc-client

pear

php-bcmath

php-bz2

php-calendar

php-cli

php-common

php-curl

php-devel

php-exif

php-fpm

php-ftp

php-gd

php-iconv

php-imap

php-ioncube6

php-litespeed

php-mbstring

php-mcrypt

php-mysqlnd

php-pdo

php-posix

php-soap

php-xml

php-zip

runtime


**PHP 7.0**

libc-client

pear

php-bcmath

php-bz2

php-calendar

php-cli

php-common

php-curl

php-devel

php-exif

php-fpm

php-ftp

php-gd

php-iconv

php-imap

php-ioncube6

php-litespeed

php-mbstring

php-mcrypt

php-mysqlnd

php-pdo

php-posix

php-soap

php-sockets

php-xml

php-zip

runtime

**Others**

apr

apr-util

cpanel-tools

documentroot

libcurl

libmcrypt

php-cli

php-cli-lsphp

profiles-cpanel

**Comment by Elshara** [comment] 2017-04-21 08:40
Well, here is an article which may help you in this regard.
https://webcache.googleusercontent.com/search?q=cache:rYNvgYSDhXYJ:https://www.namecheap.com/support/knowledgebase/article.aspx/9697/2219/php-modules-and-extensions-on-shared-hosting-servers+&cd=1&hl=en&ct=clnk&gl=ca

**Comment by Elshara** [comment] 2017-04-21 08:41
The full article was taken down, but I typed "shared hosting php
extensions" and "common php extensions" into a google search. This
mirrors exactly what I have for my hosting at the moment in the
article. I currently am using v5.6 and don't want to upgrade to php 7.

**Comment by SpiritWolfie** [comment] 2017-04-21 09:15
I still haven't been able to successfully update my live site to php 7.1 which I really want to as it offers much speed improvements etc.. but no matter what settings I use my website refuses to load to php7.1 or 7.0, yet other php 7/7.1 stuff works fine.

**Comment by DonnaScriptTechs** [comment] 2017-04-21 09:28
Ray only looked at your Apache details. There's more to the picture normally. However, for now use php 5.6 until we release 4.9.1 which should have some improvements for php7 used with our requirements. PHP7 works for me and our demo but we are tweaking some things to try to improve for those who might have issues.

**Comment by GabryNet** [comment] 2017-04-21 10:01
Thank you very much to all for reply's ... actually my fresh install works good how is it now with PHP 7 but still appears some errors like i have now and it looks is only me having it with the notification icon that opens and loads forever without showing notifications so ... i was thinking maybe is from compile mode...  i think i will just follow the advice staying with 5.6 and waiting for some new updates ... have a good day all of you !

**Comment by SpiritWolfie** [comment] 2017-04-21 19:33
@GabryNet 

I've noticed that issue too with the notification icon taking for ever to load, specifically on user profiles, it works fine on /home/ but when I go to a users profile half time it wont even pop down, and when it does it took forever.

**Comment by Elshara** [comment] 2017-04-22 07:16
Same here. It's why I down graded. Notifications refuse to load at all
for me on v7.

**Comment by GabryNet** [comment] 2017-04-22 11:35
Hi @SpiritWolfie and @Elshara ,thank you for your reply's ... i have started to feel alone in here seeing that i am the only one having this issue with a fresh install of SE Php 4.9 without touching any options in CP or install extra plugins, now i am glad that both of you have positive feedback for this problem that i also facing, indeed is the same for me , the notification icon is opening good on members home page but loading forever if i am on messages page or edit profile and if i open with firebug i receive ReferenceError: DetectMobileQuick is not defined .. i am fighting with this problem since they launched 4.9 because is very important, is about the notifications that is in the front of all the users and they will try it and see is not working, is not a minor option that can wait long time to be fixed ...hope the SE team will read this post and try to fix it ASAP ... thank you all again and have a good day !

**Comment by DonnaScriptTechs** [comment] 2017-04-24 09:08
@GabryNet the issue for the DetectMobileQuick is being addressed in another bug report. This issue for the site not loading at all is a different issue that we've not been able to reproduce. 

We aren't getting other reports of sites not working at all with php7. We'll leave this open for now though.

**Comment by Elshara** [comment] 2017-04-25 07:12
The thing is. PHP7 deprecates a lot of modules used by tons of web
scripts. I hohpe things like imagemagic aren't required by social
engine to work right. If so, it's one of the things which is
completely deprecated in php 7. But isn't in prior versions. I don't
know what each individual widget requires, it doesn't say in the
requirements.

**Comment by DonnaScriptTechs** [comment] 2017-04-25 11:16
I don't see anyplace where imagick is deprecated for PHP7.

**Comment by Elshara** [comment] 2017-04-25 11:39
That's interesting. I seen it posted here where it is mentioned as
being deprecated.
https://www.namecheap.com/support/knowledgebase/article.aspx/9697/2219/php-modules-and-extensions-on-shared-hosting-servers
If that's incorrect I apologize.

**Comment by DonnaScriptTechs** [comment] 2017-04-26 16:51
Please test with 4.9.1 once we release it. We have improved compatibility for php7. Should you still have issues after, please post a new report. Thank you!

**Closed by DonnaScriptTechs** 2017-04-26 16:51 UTC
Labels: Cannot Reproduce

**Comment by Elshara** [comment] 2017-04-26 22:09
Will do.
