### ISSUE TITLE
Mobile Issue with Multi Select Profile Questions

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#536] opened 2017-01-16 14:08 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Use a Mobile IOS device (iphone) (safari app has DONE button, chrome app has X instead of DONE, but same function)
2. … Set up a multi select profile question example to set up, fluent spoken language
3. … add a few choices, English, afrikaans, Russian, maltese, hungarian, albanian, arabic etc
4..... goto signup
5.... when you come to this question, select the very top choice then press Done on the ios keyboard. 
It will say 0 items, each time you keep going back to add it, and press done it will say 0 items.

If you go back into it, but dont select any choices, but just press done, it will say English selected (if English is the top choice)
If you go back into it, there wont be a tick shown at all, and once press done again, it says 0 items.

If however your were not choosing english at all, but instead chose Russian, if you press DONE, it will say 2 Items, and if you revisit, only Russian is ticked.

Now there are the previous /\ buttons and next \/ buttons, and these enter the fields correctly, but users always press done button, then scroll to next field. Only when Done button is used, does it cause this issue with the first choice of multiselect.

Being my first choice of multiselect is the common answer of users, and that these are mandatory questions, ive had so many people drop out from signup, and many emails saying they cant select english.

I also have a multiselect for ethnicity and as Black is the first choice, my members who are Caucasian, have selected Black also, because they have pressed DONE button, its auto added it, even tho it wasnt selected 

What versions of software are you using?
----------------------------------------
**Operating System:** … ios mobile device using safari also chrome app, basically mobile ios

**SocialEngine PHP Version:** …4.8.12

Please looking into ASAP and if could provide fix, this is very important @smazurov @alimoosavi15  @scrutinizer-auto-fixer

**Comment by poeticjustice** [comment] 2017-01-16 14:19
![image1](https://cloud.githubusercontent.com/assets/19233272/21986257/a26c403c-dbf6-11e6-97c3-aab3cd72900d.jpg)
![image2](https://cloud.githubusercontent.com/assets/19233272/21986259/a45ef8d0-dbf6-11e6-8a9d-4e0b0227a856.jpg)
![image3](https://cloud.githubusercontent.com/assets/19233272/21986274/a5b7662c-dbf6-11e6-995a-88aa1fc17fcc.jpg)
![image4](https://cloud.githubusercontent.com/assets/19233272/21986277/ab8bc660-dbf6-11e6-8074-3a0f310318ab.jpg)
![image5](https://cloud.githubusercontent.com/assets/19233272/21986280/ad20249e-dbf6-11e6-9405-ae22fc06aa8e.jpg)
![image6](https://cloud.githubusercontent.com/assets/19233272/21986284/aeccd3aa-dbf6-11e6-8116-366dcf38ee1a.jpg)
![image7](https://cloud.githubusercontent.com/assets/19233272/21986286/b02f4976-dbf6-11e6-8b5d-3716c4ba3988.jpg)

**Comment by poeticjustice** [comment] 2017-01-22 03:07
I have raised a major bug and it's affecting signup, yet this post is being ignored !!!!!!!!!

**Comment by poeticjustice** [comment] 2017-01-22 03:08
@smazurov please can you look into this or at least reply

**Comment by poeticjustice** [comment] 2017-01-23 13:59
@Khushboo016

**Comment by DonnaScriptTechs** [comment] 2017-01-27 17:45
Hello,

I've sent a note to our team regarding your issue report. Thank you for your post. Someone will respond once this is tested or if we need more information.

**Comment by poeticjustice** [comment] 2017-01-27 17:50
appreciated @DonnaScriptTechs

**Comment by DonnaScriptTechs** [comment] 2017-01-27 17:53
You're welcome. Oh, when someone is shown as subscribed (box on the right for Participants), no need to tag them as they already get notified of any comments. :) Just a tip. Saves you some time typing.

**Comment by DonnaScriptTechs** [comment] 2017-01-27 17:54
I'm still also trying to get this to work with my iPhone and localhost so I can also test.

**Comment by poeticjustice** [comment] 2017-01-27 18:10
ive made a video, just getting the link to share, https://sendvid.com/648oa5q3

**Comment by DonnaScriptTechs** [comment] 2017-01-27 18:13
Thank you. I'm sure this will help our team with seeing the issue.

**Comment by poeticjustice** [comment] 2017-01-27 18:14
appologise for massive water mark from the software on exporting.
This is happens on IOS devices

Basically as you see from the video, when IOS device goes to the multi select option, It automatically chooses the first option,

On my site every IOS user who signed up who are Caucasian have chose Black and Caucasian.
But They are not Black.

And IOS users who are black have contacted me saying, When they select black, it keeps saying ) items selected...... because it auto chooses this option when opening the multiselect, and by selecting it, its unselecting it

 
https://sendvid.com/648oa5q3

**Comment by poeticjustice** [comment] 2017-01-28 19:01
@DonnaScriptTechs out of interest, how did you get on with what i mentioned and showed in the video

**Comment by DonnaScriptTechs** [comment] 2017-01-30 15:38
Hi, I've not found a place to test it yet. Still trying. If it is a critical issue to your site, you can also send a ticket to our support via your client area for our team to check it on your site. That would be a faster way to get it checked and possibly fixed.

**Comment by DonnaScriptTechs** [comment] 2017-01-30 16:19
I can confirm this bug on our test site using an iPhone 5C.

**Comment by poeticjustice** [comment] 2017-01-30 16:27
It is critical issue, but i added and extra answer basically saying -Please Select- (which ihate having as some people think its a bug because they can select -please select-, but its tempoary

This way i could identity everyone who used an iphone or ipad etc.
Then i could delete it from their profiles by browsing members, but i have so many users now, some Caucasian user have black selected as it was the first option before placing the -please select- answer.

But it be wrong of me to go in and change, incase some Caucasian users have black heritage etc, i dont want to be seen as profiling.

I would love to contact support but years ago when i made a different social network with a partner, my partner paid $50 dollars for support and it went backand forth for ages, then anothing billing cycle occured for $50, then to be told they will look to fix in future..... after that we closed that social network down..... but a year or 2 ago i came back.... but without the partner for different project, so im very hesitant to pay for support, and believe this is the best place to voice it, as other users can see it in a public domain rather than one on one

**Comment by DonnaScriptTechs** [comment] 2017-01-30 16:31
I've already marked it a bug as I was able to test it. Our team will check on this bug and provide details on when it could be fixed in a release if they can also reproduce it. 

Thank you for your contribution.

**Comment by poeticjustice** [comment] 2017-01-30 16:33
Im really happy you confirmed this bug :) 

if the team identify's the code to add to stop this please let me know, im hopeing it doesn't take 6 months or something to wait for it in a new update. really dont want users dropping off haha

Hopefully the multiselect option will be replaced one day with tags, so when choose one it auto adds a nicely displayed tag to the field

**Comment by DonnaScriptTechs** [comment] 2017-01-30 16:35
Regarding support, I'm not sure when you had support before but our new management (as of 2014) has improved support a great deal. :)

Feel free to open a new issue with a feature request, one request at a time please. It could be considered by our team if it would be beneficial to many.

**Comment by poeticjustice** [comment] 2017-01-30 16:52
this was pre 2014 originally an we gave up after because we spent hundreds on advertising for a convention and had a major bug, plus custom developers wouldnt touch core, so we were stuck and only option was to give up.

But i had always had high hopes for SE.

James Chick did reach out to me once however and we did have a nice chat and gave suggestions......

I have opened feature requests befor via here but some where over looked and i believe had some valid points thats why i believe in tags for options selected when browsing members.

Multiselect can be such a pain, but making a selection and it adds to tags which create a great search function.

searching is hard when having single select choices too, because you dont want users signing up selecting to many options , but when searching your limited to searching that field one by one as i mentioned here

https://github.com/SocialEngine/phpv4-issues/issues/488

**Comment by DonnaScriptTechs** [comment] 2017-01-30 16:56
Ok please do open an issue for the feature request for tags. We need to keep this bug report just for the issue you addressed so that our team doesn't have a long bug report to read through and get confused for what issue is in it. We can discuss the feature request further in a different issue report. I mean yourself and our team as I might not be the one that checks that one. :)

**Comment by DonnaScriptTechs** [comment] 2017-01-30 16:57
I see the one you linked but it has more than one thing in it so it might be confusing for our team. It's best to keep each issue or bug to just one item.

**Comment by poeticjustice** [comment] 2017-02-14 20:23
Any update to this bug, because its actually a major issue, and i dont wznt to keep correcting information or have information on the site thats completely wrong regards to user info.... really is a major bug and i dont want to wait a year to see a fix really

thanks

**Comment by poeticjustice** [comment] 2017-02-18 17:11
Hi @DonnaScriptTechs 

I truely thank you for the above at locating this bug after i reported, obviously i dont know if you work for Social Engine or just a contributor.

But same time, be great to hear back about this bug as havent heard anything.

This is not exctly a small bug that can be patched in a years time, its a bug at the first stage of signing up a profile and filling in profile questions to join the website, so it kinda is a major deal....... I really hope i dont have to wait 8 months for this fix, that would be awful

**Comment by DonnaScriptTechs** [comment] 2017-02-20 15:17
Hi,

I do work for SocialEngine, as Chief Evangelist. Feel free to connect with me at our community, https://community.onsocialengine.com/profile/231316 . As for this, our core developers need to check and respond once they check it. I'm not in that department. I'm sure someone from the development team will respond. I was just testing it due to a post at the community at the time. :) I normally don't test bugs unless asked though. 

Have a great day!

**Comment by poeticjustice** [comment] 2017-02-20 16:37
@DonnaScriptTechs im actually glad you took the initiative and tested it, because i actually raised it via email to Social Engine months before posting here.

I totally forgot about it because i had no reply, until i noticed the issue again, and was forced to put it here so others could see it.

Just scared to message social engine directly as I feel i'd either be ignored or required to pay for support to a bug.

**Comment by DonnaScriptTechs** [comment] 2017-02-20 16:42
I'm sorry you feel ignored as it is never our intent to ignore anyone. It is possible that a glitch can happen when sending a ticket and it doesn't reach us; or, sometimes answers go to spam. Sending the ticket from your account should work fine 99% of the time. Hiccups can happen though. You can always check with me at our community or open a live chat during chat hours, to check on tickets. :) If you have more feedback or questions not related to this bug, please feel free to get with me at the community as too may responses here can delay our developers as they have to read every comment. 

Have a wonderful Monday!

**Comment by Elshara** [comment] 2017-02-22 09:58
I can confirm this also. Using Android Google Pixil.

**Comment by poeticjustice** [comment] 2017-02-25 18:27
@Elshara this does the same with Android Google Pixil.
Dammm have Android Google Pixil changed the format or the way android is specifically for this device so that this happens, i thought it was just apple ios

**Comment by poeticjustice** [comment] 2017-02-25 18:28
Hi @DonnaScriptTechs there is absolutely no way of joining your community you mentioned https://community.onsocialengine.com/profile/231316
https://community.onsocialengine.com/

Only a sign in button, no signup at all

**Comment by DonnaScriptTechs** [comment] 2017-02-27 17:29
Hi, 

Our community is invite only. Please send a ticket from your account so that we can invite you to it.

**Comment by Elshara** [comment] 2017-02-27 17:34
Yeah I know. The issue is strictly to do with the mobile plugin. I can
even reproduce the same when switching from desktop to mobile in the
windows 10 pc I have.
Donna did invite me to her own community perhaps you could join there.

**Comment by poeticjustice** [comment] 2017-02-28 13:48
just found another major issue with multiselect now, my site is gunna go down if not fixed

And @DonnaScriptTechs there is no way im paying $50 to raise a ticket to receive an invite to that community as much as id like to and contribute, but now way paying $50, i have major issues which are SE bugs and im not paying $50 to be told it be in next update, fixes need to be done now

**Comment by poeticjustice** [comment] 2017-02-28 13:48
can i have direct emails please, these bugs are crazy!!!!!!!! need fix now

**Comment by Elshara** [comment] 2017-02-28 18:42
What's the bug?

**Comment by DonnaScriptTechs** [comment] 2017-02-28 18:49
I just checked your ticket and that email already has an account at our community. You just need to do the forgot password if you don't have the password @poeticjustice  :)

**Comment by poeticjustice** [comment] 2017-02-28 22:38
@Elshara if you go to this https://github.com/SocialEngine/phpv4-issues/issues/580 you will see the other bug

**Comment by Elshara** [comment] 2017-03-01 00:13
Thanks I'll check it out.

**Comment by poeticjustice** [comment] 2017-03-01 00:17
@elshara Social Engine just sent me a long email and have confirmed it is a bug, either I wait for a fix or I pay support to get on it asap :(

**Comment by Elshara** [comment] 2017-03-01 00:34
There just responded.

**Comment by Khushboo016** [comment] 2017-03-03 12:13
Hi @poeticjustice @Elshara, This is to update you that this bug is going to be fixed in our upcoming release 4.9. So, this would not be faced afterward.

 Thanks & Regards!

**Comment by poeticjustice** [comment] 2017-03-03 15:40
awesome :) will issue mentioned in #580 also be in release 4.9 @Khushboo016

**Comment by Elshara** [comment] 2017-03-03 17:43
lol

**Comment by Khushboo016** [comment] 2017-03-06 06:45
Hi @poeticjustice, Yes, we're putting all our efforts to fix this issue (mentioned in #580) too in 4.9.

**Comment by DonnaScriptTechs** [comment] 2017-04-04 17:05
This is fixed for 4.9 when it is released. Once this version is released, if you still have issues, please open a new bug report at that time.

**Closed by DonnaScriptTechs** 2017-04-04 17:05 UTC
Labels: bug

**Comment by poeticjustice** [comment] 2017-04-04 18:39
Ohhhh fixed HElllllllllllllllllllll yea, i can finally delete the selectable -please select- option then wahooooo, cant wait, was such an annoying bug lol

**Comment by Elshara** [comment] 2017-04-05 06:50
Awesome.
