### ISSUE TITLE
Disallow member to change username not working

### ISSUE THREAD

**Issue by PennyRoomHost** [SocialEngine/phpv4-issues#267] opened 2015-08-31 21:39 UTC
Option to NOT allow members to change their username is checked as "no" under member level options, however, members are still changing their usernames which has resulted in much confusion. How do I MAKE SURE they cannot change their name?

**Comment by Anshuse** [comment] 2015-09-01 10:03
Hi @PennyRoomHost , we're sorry to say but we're not able to reproduce this issue at our end. Please make sure that the Member (with which you're testing this feature) belongs to the particular "Member Level" for which you've disabled "Allow username changes?" field. It means that if you've disabled "Allow username changes" for "Default Member Level" then members of Default Member Level will not be able to change their usernames.

**Comment by PennyRoomHost** [comment] 2015-09-01 17:32
I have disallowed for all regular member levels, and yes this member is in that group. And they are changing BOTH usernames AND display names. 
![bidderlevels](https://cloud.githubusercontent.com/assets/14062493/9611459/ba773e5a-50ad-11e5-8d09-d5add08e46cb.JPG)
![avitprname](https://cloud.githubusercontent.com/assets/14062493/9611468/bf5b3ade-50ad-11e5-9e06-8863f2b9bf72.JPG)
any more suggestions as to where to look for a resolution would be appreciated.

**Comment by Anshuse** [comment] 2015-09-03 09:53
Hi @PennyRoomHost , We've checked this issue on our demo site http://demo.socialengine.com and on our local set-up also but we're not able to reproduce this issue at our end. So, we suggest you to email us at support@socialengine.com and our staff will check the issue on your site. If it will be installation specific issue then they will guide you if you need to open a support ticket for our support team to look into this. Thanks!

**Closed by Anshuse** 2015-09-03 09:53 UTC
Labels: invalid
