### ISSUE TITLE
Activity type setting for group topics are neglected, intermingled with user profile post settings

### ISSUE THREAD

**Issue by rwetzlmayr** [SocialEngine/phpv4-issues#417] opened 2016-05-03 07:09 UTC
## What are the steps to reproduce this issue?
1. Go to the admin action type setting **When a user (subject) posts a message to another user's profile (object).** (http://www.example.com/admin/activity/settings/types/type/post)
2. Check **Display > Main feed** for this action type.
3. Post a new group topic or reply to an existing **group** topic.
4. Browse the main activity feed and find a new entry for the group post created in the previous step.
5. Go to the admin action type setting **When a user (subject) posts a message to another user's profile (object).** (http://www.example.com/admin/activity/settings/types/type/post)
6. Uncheck **Display > Main feed** for this action type.
7. Browse the main activity feed once more.
## What happens?

The main activity no longer shows activities relating to new group posts or replies to group posts.
## What were you expecting to happen?

I was expecting that the display of these activities in the main feed is controlled by the two appropriately labelled settings in **Activity Feed Item Type Settings**:
1. **When a user (subject) creates a new topic in a group (object).** (`group_topic_create`)
2. **When a user (subject) replies to a topic in a group (object).** (`group_topic_reply`)

Apparently, these two action type settings do not work as intended.
## Any other comments?

I think that new group topics and replies to existing group topics create an entry in the `engine4_activity_stream` table with `type` set to `post` and not with `type` set to `group_topic_create` or `group_topic_reply`, resp. 

Thus the activity type setting **When a user (subject) posts a message to another user's profile (object).** is also taken into account in `\Activity_Model_DbTable_Actions::getActivity` for **group** postings: They are filtered out when this settings **Display > Main feed** checkbox is unchecked.
## What versions of software are you using?

**SocialEngine PHP Version:** 4.8.10

**Comment by Khushboo016** [comment] 2016-05-06 05:53
Hi @rwetzlmayr , We are not able to reproduce this issue at our end after following your steps to reproduce the same. 
 First we checked the **Display > Main feed** for the below action types from "Activity Feed Item Type Settings" section:
- **When a user (subject) posts a message to another user's profile (object).** 

- **When a user (subject) creates a new topic in a group (object). (group_topic_create)**

- **When a user (subject) replies to a topic in a group (object). (group_topic_reply)** 

Then posted a new topic "Test Group 4" in an existing group and then posted a new reply to this topic, and when we checked in the Main Activity Feed, we found new entries there for the new group topic post and for reply to this topic.

Then, we unchecked the **Display > Main feed** for the action type **When a user (subject) posts a message to another user's profile (object)** and again checked on the Members Home Page, the Main feed still kept showing entries for new group posts and replies to group posts as shown in the below screenshot: 
![group](https://cloud.githubusercontent.com/assets/18209340/15065065/13349e46-1379-11e6-98fe-e7671fe3342e.png)

Also, we checked in the table `engine4_activity_stream` in the database of the site, and found the entries of the new group topics and replies to existing group topics with type `group_topic_create` and `group_topic_reply`, respectively as shown in the below screenshot:

![database_entries](https://cloud.githubusercontent.com/assets/18209340/15065070/2320e5d0-1379-11e6-8d56-ec88494fee75.png)


So, this issue is not reproducing at our side, so we suggest that if you are still facing the same issue then you can open a support ticket for this at https://www.socialengine.com/client/ticket/create or you can also email us at support@socialengine.com .

Thanks!

**Comment by rwetzlmayr** [comment] 2016-05-17 16:07
You are right, and I must rephrase my issue.

Please replace step 3 ("Post a new group topic or reply to an existing group topic.") from my "steps to reproduce" list. It should read:

**Share a new update to a group**

![screenshot - 17 05 2016 17_53_37](https://cloud.githubusercontent.com/assets/357054/15329231/3ca02f6a-1c58-11e6-8350-5337db510b1e.png)

If **When a user (subject) posts a message to another user's profile (object).** is checked this update is displayed in the main activity feed:

![screenshot - 17 05 2016 17_56_12](https://cloud.githubusercontent.com/assets/357054/15329330/997f2eb6-1c58-11e6-83b8-d5e784b659e5.png)

Once  **When a user (subject) posts a message to another user's profile (object).** is unchecked this update is no longer displayed in the main activity feed.

This issue boils down to the misleading phrasing of the activity type setting "When a user (subject) posts a message to another user's profile (object)" as this setting covers both posts to another user's profile *and to a group profile*.

Additionally, I hadn't grokked the difference between group discussions and group updates (head-> desk) until now.

**Comment by smazurov** [comment] 2016-05-17 20:28
Is changing wording of those settings good enough, or should we have separate settings for user's profile and group?

**Comment by rwetzlmayr** [comment] 2016-05-18 06:06
I very much plead for separating this setting into two separate options. We usually even have two options for creating or replying to one object class like e.g. forum topics so it is merely orthogonal to not let one single option control two object classes (users and groups in this issue's case).

**Comment by Elshara** [comment] 2016-06-25 00:50
This issue can be reproduced under event profiles as well.
I'm actually one to vote for group and event activity feeds to be removed entirely. It totally makes productivity impossible. To be replaced with comment walls. Same goes for profiles. Why should another user be able to post an update to someone elses activity feed? Replace that third party posting capability with comment walls. The link to profile comments page, group comments page and event comments page respectively. Alternatively, allow the ability to allow all members the need to send messages to groups and events as an alternative update function.

**Comment by Khushboo016** [comment] 2016-06-28 17:55
Hi @rwetzlmayr , @Elshara , We have added this suggestion in our internal feature tracker for internal team discussion regarding its implementation in our future releases.

Thanks!

**Comment by DonnaScriptTechs** [comment] 2017-04-08 15:03
This is implemented for 4.9.0 when it is released.

**Closed by DonnaScriptTechs** 2017-04-08 15:03 UTC

**Comment by Elshara** [comment] 2017-04-10 22:08
Awesome!
