### ISSUE TITLE
Signup process: Member Account Approved email template is not sent

### ISSUE THREAD

**Issue by auntialias** [SocialEngine/phpv4-issues#287] opened 2015-10-26 05:52 UTC
SocialEngine 4.8.9
**Member Signup Process for new accounts that require Admin Approval: The Mail Template _Member Account Approved_ is not sent to new member.**

## Settings that failed to produce email
In Control Panel > Settings > Signup Process > Step 2: Create Account, set these configuration options (tested 2 different ways; see 4th bullet point)
* Enable Profile Address = YES
* **Auto-Approve Members = NO**
* **Notify Admin by email = YES**
* Invite Only? = YES  
_or_  
Invite Only? = YES ADMINS must invite (i.e, members cannot invite)

(here are the rest of the settings, FYI)

* Verify Email Address = YES
* TOS = No
* Generate Random Passwords = YES
* Check Invite Email = YES

## Emails that WERE generated
Since this was tested under two conditions, I'll describe them both:

### Invite Condition
1. Admin sends invite to new potential member.
2. New member receives email, clicks to go to site.  
Email address and invite code are pre-populated in form.
3. New member fills out username + initial profile. Clicks submit button.
4. Page refreshes and two emails are sent (see Step 7 for second email).
   * Page refresh: blurb saying varification email was sent. Once you do that, AND once you've been approved, you'll be able to sign in.
   * Email is sent to person: has a link to click, email address, and password.  
5. User clicks link in email, goes to website.   
Page says, "Your account has been verified. Please wait to be redirected or click here to login."  
User waits or clicks, and the page refreshes to a login screen
6. User enters login credentials, clicks Sign In button.  
Page refreshes, saying **This account still requires admin approval**
clickOnce user clicks link, and submits password, User is told to WAIT  
7. (In step 4, 2 emails are sent. This is about the second email) Email is sent to SuperAdmin, saying "welcome new member" --See [this separate bug report] (https://github.com/SocialEngine/phpv4-issues/issues/286) for more info why the email in this step is a FAIL.
8. At what ever time Admin finally gets around to approving the new member, member is finally able to log in. This would, I expect, be the time that the **Member Account Approved** email (see Control Panel > Settings > Mail Templates and Choose Message _Member Account Approved_)    
FAIL.  
**NO EMAIL NOTIFICATION IS SENT TO MEMBER. NONE.**  :rage:  :rage:  :rage:     
If, because of **compounding effect of Bug** mentioned in Step 7, Admin takes sweet time to approve member, **new member does not know if the new account has been approved.**  :rage:  :rage:  :rage:  :rage:  :rage:  :rage:   :rage:    

### Signup Condition (no invite)
1. Potential new member arrives at site, begins to sign up (user name, profile).
2. Continue as from step 4, above (page refreshes, two emails are generated)

Results are identical: **Epic. Fail. NO EMAIL NOTIFICATION TO MEMBER**
:rage: :rage:  :rage:  :rage:  :rage:  :rage:  :rage:

## FIX
Fix SocialEngine so that it actually sends the damn **Member Account Approved** email.

**Comment by auntialias** [comment] 2015-10-26 05:58
Obvious workflow solution for first condition (Admin sends invite—User signs up) is to NOT require second approval step. This will be my solution for the site I'm building. **But my solution does not fix the bug described here.**

**Comment by Anshuse** [comment] 2015-11-18 07:41
Hi @auntialias ,

We've checked this issue using both use cases (with and without Invite along with all other settings as you specified above) and we received an email regarding account approval. 

![demo](https://cloud.githubusercontent.com/assets/11085507/11235245/c2f13812-8df5-11e5-8d9f-a81b5068f7c6.png)


As we're not able to reproduce this issue at our end so, we're closing this case.

Thanks!

**Closed by Anshuse** 2015-11-18 07:41 UTC
