### ISSUE TITLE
Ad Campaigns don't respect networks

### ISSUE THREAD

**Issue by angelinfante** [SocialEngine/phpv4-issues#525] opened 2016-12-25 23:38 UTC
As HTML content can't be translated in layout editor, I use ads to display different HTML content to different countries (networks). All the members in my website belong to one network that is assigned matching the member's country. All of them share an additional network named "International".

What are the steps to reproduce this issue?
-------------------------------------------
1. Create an ad targeting some networks except "International"
2. Create another ad targeting the rest of networks except "International"
3. Place both ads in the same page
4. Log in with a member that should view only one ad

What happens?
-------------
Both ads are visible, although member should view only one of them

What were you expecting to happen?
----------------------------------
See only one of the ads (the one configured for the network of the member)

What versions of software are you using?
----------------------------------------
**Operating System:** Amazon Linux

**SocialEngine PHP Version:** 4.8.12

**Comment by Khushboo016** [comment] 2016-12-26 13:22
Hi @angelinfante, We've checked the above issue at our end and are not able to reproduce this as the advertisements are shown only to the members which belong to the networks specified for the respective ad campaigns. But we found that if a member level is selected for an ad campaign then the advertisements of that ad campaign are shown to all the members of that member level whether they belong to the network/networks specified for that campaign or not, while this should function in such a way that the advertisements should be shown to the members who belong to the Member level specified and at the same time belong to the network specified for that ad campaign. Hope you understand my point here. So, we've forwarded this point to our development team for discussion.

Thanks & Regards!

**Comment by angelinfante** [comment] 2016-12-26 14:14
Yes, that's the point, would be nice to have that improvement. Thank you.

**Comment by Elshara** [comment] 2017-02-22 10:05
I support this.

**Comment by shivani2910** [comment] 2017-04-11 08:20
This is fixed in 4.9 when it's released.

**Closed by shivani2910** 2017-04-11 08:20 UTC

**Comment by Elshara** [comment] 2017-04-11 16:32
Awesome!
