### ISSUE TITLE
Complex formatted strings lost when language packs converted to PHP arrays

### ISSUE THREAD

**Issue by coder4web** [SocialEngine/phpv4-issues#762] opened 2017-06-15 18:14 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Check "Translation Performance" in "Performance & Caching" tab in the admin area.

What happens?
-------------
Strings with complex format will be lost in .php files
See example for /signup page in Russian: https://prnt.sc/fk6yiz

What were you expecting to happen?
----------------------------------
Proper translation of all strings from .csv files

Any logs, error output, etc?
----------------------------
This is not error, just bug.

Any other comments?
-------------------
Example of strings with complex format (see for double quotes "" inside strings):
1) "This will be the end of your profile link, for example: <br /> <span id=""profile_address"">http://%s</span>";"Это будет служить адресом Вашей страницы, например: <br /> <span id=""profile_address"">http://%s</span> "
2) "I have read and agree to the <a target=""_blank"" href=""%s/help/terms"">terms of service</a>.";"Я прочитал и согласен с <a target=""_blank"" href=""%s/help/terms"">правилами сайта</a>. "
and so on...

Translation is full when .csv files (not .php arrays) used:
https://prnt.sc/fk6xv8

What versions of software are you using?
----------------------------------------
**Operating System:** Doesn't matter.

**SocialEngine PHP Version:** Up to 4.9.2

**Comment by DonnaScriptTechs** [comment] 2017-06-16 09:20
I believe this is a duplicate of one of these:
https://github.com/SocialEngine/phpv4-issues/issues/140
https://github.com/SocialEngine/phpv4-issues/issues/247

Please look those over and let us know.

**Comment by coder4web** [comment] 2017-06-16 09:28
Yes, all these bugs definitely related. And both still active :(

**Comment by DonnaScriptTechs** [comment] 2017-06-16 09:29
They are marked for 4.9.3 and so will be fixed when it is released. Is this the same as the others though? if so, I will mark a duplicate.

**Comment by coder4web** [comment] 2017-06-16 09:30
Yes, please.

**Comment by DonnaScriptTechs** [comment] 2017-06-16 09:38
Thank you!

**Closed** 2017-06-16 09:38 UTC
Labels: Duplicate
