### ISSUE TITLE
Mass Auto Approve and Auto delete not working in #Core

### ISSUE THREAD

**Issue by wtoalabi** [SocialEngine/phpv4-issues#177] opened 2015-07-11 04:10 UTC
On Members page in admin panel, mass selection of members to delete or to approve is not working.
Thanks
#core

**Comment by Anshuse** [comment] 2015-07-16 13:50
Hi @wtoalabi , If you mean to say that when you click on small check-box just before the "ID" column is not working then we're not able to reproduce this issue at our end and issue exists specifically in your installation and you may file a support ticket along with your site details, our staff will be happy to help you out.

If you meant to something else then please clarify.

**Comment by shivani2910** [comment] 2015-07-23 03:41
Hi @wtoalabi, since we didn't get your response, we're closing this issue .

**Closed by shivani2910** 2015-07-23 03:41 UTC
Labels: need feedback

**Comment by Elshara** [comment] 2015-08-12 18:30
I can confirm this is a local issue because the selection does work. However, the selection can only be 10 at a time. No way to change this.

**Comment by shivani2910** [comment] 2015-08-13 08:29
@Elshara you can apply below code level change to be able to select more user users at a time in Manage Members section:

Please open file ```application/modules/User/controllers/AdminManageController.php```

and search for below code at line no. 80 (approx):
```$this->view->paginator = $paginator->setCurrentPageNumber( $page );```

Now, place below code just above the code mentioned above (where "X" is the number of users that you want to display on one page):

``` $paginator->setItemCountPerPage('X'); ```

Hope that helps! Thanks.

**Comment by Elshara** [comment] 2015-08-13 17:17
Thanks this solved the issue!

**Comment by Elshara** [comment] 2015-08-13 17:17
Is there no way to add a global variable field in control panel
settings about this?

**Comment by wtoalabi** [comment] 2015-08-13 17:20
Thats awesome! Thanks for your help...will check now!

**Comment by Elshara** [comment] 2015-08-13 17:35
Cheers.
