### ISSUE TITLE
Improve Default Email Notifications Setting for All Users

### ISSUE THREAD

**Issue by nviitala** [SocialEngine/phpv4-issues#734] opened 2017-05-10 16:40 UTC
I have 40 000 members on my site. The default has been to send all email notifications.

Now if I want to set all email notifications as disabled as default, there will be no change to the users - no matter has the user touched or not her/his notification settings.

However, for every new user, the system will generate automatically almost 40 records to the "activity_notificationsettings" database table, with email column as "0" for not to receive these mails.

And again, if I change the defaults, it doesn't have an affect to these previously registered members. Some who have now emails as disabled and some have those enabled - even if they haven't touched their settings.

Currently also to activity_notificationsettings table are added only rows when some email notification is disabled. That makes even manually editing the user notification settings really hard.

It would be much better, if the default settings would affect EVERY user, who hasn't touched to her / his own notification settings. Not just the new users, which sign up after the change. So only member's own changes would be marked to the database.

It would also be better, if the activity_notificationsettings table would show 0/1, 1 when user wants the notification and 0 when he doesn't want. Not just 0 when the user has marked not to want to receive a specific notification.

**SocialEngine PHP Version:** 4.9

**Comment by gsf00001** [comment] 2017-05-10 17:52
Yes, the entire notifications and email notifications sections should be changed, and include much more flexibility and functionality, such as what you mentioned and more.  There should be controls for 'who this affects' = existing users, new users, both, etc.  One method (since notifications and emails notifications are so related) is to display a table with columns for notifications and email notifications, with either columns below each of these 2 primary headings for each of the different settings (new users, etc.) or a code that represents which (1=new, 2=existing, 3=all, 0=off, etc.).  There could also be some global settings too as well as settings to control if these ADMIN settings override existing User settings.   This and what you wrote could just be starting points.  Oh - and this should be flexible enough to allow easy integration of Plugins too - so those notifications can be controlled via the same area/settings.

The point is that ADMIN should have much better, detailed control over all notifications - especially to minimize site traffic and email traffic however they choose.  

Anyway, yes - thanks for posting this nviitala :)

**Comment by DonnaScriptTechs** [comment] 2017-05-10 20:06
https://github.com/SocialEngine/phpv4-issues/issues/566 This is a duplicate of that. Please search before posting to avoid duplicates. The feature request is a good suggestion. Please feel free to comment in the original one.

**Closed by DonnaScriptTechs** 2017-05-10 20:06 UTC
