### ISSUE TITLE
Feature request - Logout redirect option, or Logout page in Layout editor

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#708] opened 2017-04-25 01:25 UTC
Hi

Feature Request.

Be great to have a page for sign out to be added to layout editor

Purely as we could place ads on the sign out page, or add HMTL code.
Example some installs of SE may be in a subfolder, and with a sign out page in the layout editor, html can be used to redirect to the main display page.

Or an option in settings that asks for a sign out redirect page

**Comment by Elshara** [comment] 2017-04-25 07:55
I agree. This would be nice to put code there so you can track if
members use it prior to being inactive.

**Comment by Elshara** [comment] 2017-04-25 07:56
I was thinking crazy egg integration would go nicely for social engine
websites, with its main feature tracking sign up sign in and sign out
pages.

**Comment by gsf00001** [comment] 2017-04-26 07:32
is this the same as #627?

**Comment by Elshara** [comment] 2017-04-26 08:01
That's what I thought when I read it I thought I seen it elsewhere.

**Comment by Khushboo016** [comment] 2017-04-27 06:34
Hi @poeticjustice, This is a duplicate of issue https://github.com/SocialEngine/phpv4-issues/issues/627, so I am closing it. Please do not open multiple cases for the same issue.

Thanks & Regards!

**Closed** 2017-04-27 06:34 UTC
Labels: Duplicate

**Comment by Elshara** [comment] 2017-04-29 14:15
:)
