### ISSUE TITLE
Add a Option to Make Activity Items Likeable but not Commentable

### ISSUE THREAD

**Issue by leandrotavaresrocha** [SocialEngine/phpv4-issues#584] opened 2017-03-02 01:29 UTC
Hello,

Actually SE has only an option to make activity items shareable or not. I would like to propose the addition of a new setting to make possible a activity item be likeable but not commentable.

The reason is simple, certains types of content are not good to be commentable like a forum topic, but they are nice to be likeable and in the actual scenario if you disable comments changing the value in the column commentable in the activity_type_action table to zero it disable not only comments but also likes.

**Comment by Elshara** [comment] 2017-03-02 23:56
The problem is comments and likes are integrated into the same module. You can't enable one without disabling the other. Now if they were separate modules, this should be no problem to implement.
I was actually hoping the reverse could be set up. To be able to comment but disable liking. Because say you like an item, but you like the fact the item was posted to the feed, which is a duplicate of the actual item itself, you didn't really like the item you were interested in. You liked its feed entry instead. I think such duplicate actions should be integrated into the same item, so it brings up the like option for the item you wish to like, not the option to like the fact the item was posted to the feed.
The share option is just useless, it just spams your activity feed with the post of someone else. I mean who honestly goes to profile pages to check what activity feeds someone has posted, when they have all the other modules to consider as well, assuming you added them to their profile page in layout editor.
Either way it is a good idea.

**Comment by Khushboo016** [comment] 2017-03-03 12:51
Hi @leandrotavaresrocha, @Elshara, 

We suggest you do code changes at your end to make this feature possible to be able to make an activity item/post likable but not comment-able or comment-able but not likable. Because this feature may be useful for your community, but in general this does not seem to be a very useful/significant feature and also we have not received any other requests from clients for its implementation. So, we are sorry, but we are not considering this for now.

Thanks & Regards!

**Closed** 2017-03-03 12:52 UTC

**Comment by leandrotavaresrocha** [comment] 2017-03-03 13:03
@Khushboo016, I already talked with two developers about this but they said that is not possible to solve this issue without "reinvent" the core basic module the work with likes and comments.  If I do all the core codes changes that people are suggest to me for these small things I will not have social engine anymore but a complete different script.

**Comment by Elshara** [comment] 2017-03-03 18:16
Not true, not true at all.
If you get someone to develop an advanced comments plug in and a
separate likes plugin. Also get them to develop a separate advanced
activity feeds module. Then just mix and match it and you basically
get similar functionality. It's just you have a lot more settings to
play with for each module both in terms of member levels as well as
global settings respectively.
Regarding "this isn't a request we have gotten from a lot of other
clients" funny thing is, we're two of such clientele already. More are
probably on their way. The issue is, you don't want to pay a developer
to separate the modules from comments and likes. Unfortunately, that's
the hardest part to do here, and it just is a matter of implementing a
simple code change afterwords before the old unified comments and like
plugin gets replaced by the new individual modules. Not only would
this improve social engine by doing simple things for users like
respectively allowing users to get notifications on whether or not
they want to receive them if someone responds to their activity on
site, and where such responses are placed, but also, it makes no
difference to existing database queries already displayed as entries
based on who has commented and who has liked what because the core
information never gets removed if the features themselves do.
I've suspected for quite some time now on just how integrated the
comments and likes module is with the activity feed. It's almost
exclusively related to it. Removing it from the core and replacing it
with separate plugins to achieve the same or similar functionality, to
do even more things with than its previous and now current means of
handling operations on a regular basis, would be seemingly as simple
as updating the files which displays where to send post interaction
queries. You have the choice of just making it function the same as
the forum module, which is the only module which does not use the
comments and like plugin at all. Or you could replicate what companies
like Social Engine Add Ons, Rad Codes and Hire Experts has done, even
You Net, which is to create shared modules to handle independent
tasks. The only difference being, you're using a hook to connect the
new plugin to the same database entries for the existing plugin,
something other third parties has also been able to achieve since day
one for their advanced line up of plugins to address such a problem of
core ones being too limited. The only reason why their advanced
comments plugin to date has not been to connect to the same database
as old comments, is because they aren't selling their shiny new
advanced activity feeds plugin with the advanced comments plugins to
make such plus likes available to toggle. More to the point, if
someone uninstalls their plugin, any features dependent on it won't be
available if the same database exists, which is why plugin developers
try to make their modules least dependent on existing database tables
to try to combat uninstallation procedures should any arise. To date,
people would have to remove database entries manually which mention to
some extent, the module in question, but won't completely remove its
influence from existing tables because the data is too spiratically
spread apart. So as you can see, a head ache for developers is the
lack of core features available to extend, and should comments and
likes and the activity feed option of just being able to separately
switch on or off the ability to comment or like a post not just in the
activity feed, but through other modules as well somehow be
implemented, then it is as simple as making the plugins separate from
one another in terms of functionality, it seems so simple a child
could figure it out. This leaves social engine core with the ability
to create a nested comments plugin, as well as a reactions plugin
instead of just like and unlike. It allows the introduction of a
subscription plugin to handle emails based on the two response
plugins, comments and likes more easily and add it as a task scheduler
entry in the job queue section of emails if available, the background
mailer application.
I understand you're currently swamped for requests, but it would be
worth your while to consider separating the two regularly used
functionality at some point. Even if activity feed posting options get
bumped somehow further in to potential improvement territory. It could
only be a win win situation for you. I do have social engine best
interests at heart as I say this. That which doesn't weaken us makes
us stronger.
