### ISSUE TITLE
Unapproving someone does not remove them from website

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#764] opened 2017-06-26 22:39 UTC
Step 1: Unapprove a user that is currently signed in fully
Step 2: Check and notice user is still freely able to use the website until they log out

I expect the user to be kicked from the website the moment I unapproved them

There is no way to truly kick a user off the website from what I can see, flipping it to maintenance mode and back doesn't kick them off ether.

Why does this matter?
This allows illegal activity to cont from the user if they are breaking the laws, or ToS
or harassment to cont, A user who has been unapproved should not be able to freely use the website and view its contents until they log out.

I have tested this on both dev and live, On my test account that I unapproved I can use the plugins, none plugins, forums, etc

**Comment by DonnaScriptTechs** [comment] 2017-06-27 11:32
I cannot reproduce this. In order to disable a user, you must unselect "Enabled." Once done, the member is unable to be on the site. For more information, please see our documentation, http://support.socialengine.com/php/customer/portal/articles/1654853-admin-panel---manage-&amp;gt;-members .

**Comment by SpiritWolfie** [comment] 2017-06-27 18:36
I have unselected disabled, and they are still on the website for a bit

I also get a error when I try to delete someone.

**Comment by DonnaScriptTechs** [comment] 2017-06-28 13:09
When I unselect Disabled, my user is kicked off the site. A page refresh shows to log in. Each test I've done.

**Comment by DonnaScriptTechs** [comment] 2017-07-06 11:55
Our team is unable to reproduce this. We had other team members test. As we are closing this github area, please post at our community if you still have this issue.

**Closed by DonnaScriptTechs** 2017-07-06 11:55 UTC
Labels: Cannot Reproduce
