### ISSUE TITLE
URL Rewriting

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#199] opened 2015-07-26 23:52 UTC
I wish urls of content could have their own words of the title instead of random numbers of things for all content. It might make them longer, but it is worth it. For example, the url of a group could be something like mysite.com/community/index/social-engine-example or the url of a photo could simply be mysite.com/photos/photo1 where not only the name of the file, but the directory could be altered so that it tells the story relative to language manager perhaps.

**Comment by smazurov** [comment] 2015-07-27 00:18
duplicate of #149

**Closed by smazurov** 2015-07-27 00:18 UTC

**Comment by Elshara** [comment] 2015-07-27 02:16
Oh okay.
