### ISSUE TITLE
Token issue in SE 4.8.11: When click on Add Friend Button in "View Recent Updates" link on Member Home Page

### ISSUE THREAD

**Issue by Vaibhavagarwal0807** [SocialEngine/phpv4-issues#431] opened 2016-06-01 06:45 UTC
I have download latest version of SE4.8.11 and I have set up Fresh SE4.8.11 on my Local Server.

I have faced a issue when click on "Add Fiend" Button in "Recent Updates" page and it is giving "Invalid Data" Error. You can open this page by this URL: SITEURL/activity/notifications

It is working fine on your SocialEngine Demo site.

According to SE change log: https://s3.amazonaws.com/se4-downloads/changelog_4.8.11.html

application/libraries/Engine/Form.php - Added method: setSecretSalt and set unique salt for Hash element

I have opened above file and search "set unique salt" function, but did not found. Only "setSecretSalt" function is exist in above file path.

**Comment by crossy4life** [comment] 2016-06-03 07:09
i can confirm this error as its currently happening on two of my SE Sites since i have upgraded to the latest version

**Comment by shivani2910** [comment] 2016-06-03 11:45
Hi @Vaibhavagarwal0807 and @crossy4life, we've posted a fix for this issue here: https://github.com/SocialEngine/phpv4-issues/issues/436

Please download the .zip file provided in this issue and get this issue fixed on your websites.

Also, we'll include this fix soon in our next release of SocialEngine PHP. 

Thanks & Regards,
Shivani

**Closed by shivani2910** 2016-06-03 11:45 UTC
