### ISSUE TITLE
profile questions - multi select more issues found

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#580] opened 2017-02-28 13:09 UTC
reported previous a massive issue with multiselect, but now ive found what has to be the most annoying issue ever.

its actually ridiculous how outdated this is now. or little thought gone into it.

I was doing a search on my site using multi select, thought lets see who is skilled in for example 
Horse riding, and Archery and Water Skiing..... selected these 3

and it returned 0 Users

I was like odd because i know i have users with those skills

its because the search will ONLY show people who have added exactly them 3 together.

rather than display users having horse riding skill, archery, and water skiing.

This is just terrible

Example if it was a dating site

Your preference of dating is Black, and Oriental

you search multi-select and choose Black and Oriental, and it comes back 0 members found

WTF like seriously why is it not displaying both black and oriental
thats what it should be showing, not users who ONLY add them as a combo, that is the most ridiculous search ever!!!

Please thoughts @smazurov @alimoosavi15  @scrutinizer-auto-fixer  @DonnaScriptTechs @RaymondBenc

**Comment by poeticjustice** [comment] 2017-02-28 13:44
right this needs to be addressed asap, im not paying $50 to raise a ticket nor can this wait!!!!

these bugs with multiselect is ridiculous

example that it should work like mentioned is your specific question

"interested in"

I added it to my questions, i made sure in profile questions , that i selected women

I searched in the field search interested i women and men both ticked, and my profile is displayed because i put, interested in Women.

but in my example above, if Your preference of dating is Black, and Oriental

and you multi select or even multi checkbox it like your specific question, 

It wont show black or oriental people,

Only shows people who have selected both!!! 

It should show black and oriental as well as people who selected black and oriental together!

This needs to be fixed asap as in now!!!

**Comment by poeticjustice** [comment] 2017-02-28 14:20
saying this, even your specific questions is bugged

if you select interested in women, but search interested in men, profiles still display lol

**Comment by DonnaScriptTechs** [comment] 2017-02-28 15:55
I just tested this on my 4.8.13 site. I cannot reproduce an issue. Perhaps I tested it wrong.
I made a multi-select profile question of "Favorite foods".
The three options I made are: Pizza, Hamburgers, Chocolate.

User A chose Pizza, Chocolate
User B chose Chocolate

User B went to the member browse and searched for those that like Chocolate and it brought up both User A and User B. 

Is that the proper way to test this?

**Comment by DonnaScriptTechs** [comment] 2017-02-28 15:56
Please make sure you are using the most current version in your tests and that no third party products are interfering as my tests are on a site with no third party products, using most current version.

**Comment by DonnaScriptTechs** [comment] 2017-02-28 16:02
Oh ok I see. If the search is for Pizza and Chocolate it only shows User A. User A and Use B should both show. I can confirm the issue as you have described it.

**Comment by poeticjustice** [comment] 2017-02-28 22:34
surely has to be a bug @DonnaScriptTechs 

it make no sense if it was coded that way.
100% a bug because it would deem that option completely pointless!

**Comment by Elshara** [comment] 2017-03-01 00:24
I can confirm this as well. I am on 4.8.13 and yeah the issue is due to a search display problem. I understand why it is happening.
The select list boxes don't work well with search. I believe the cause of this issue is because the list boxes are treated as a single search query, as if you were to write those exact words without separate searches. Check boxes are implemented by search fields so that you can check whatever and it shows up as a separate search query, even though all the queries made, singular or multiple, appear in one results page. Select boxes just appear as one field entry, so it is impossible for them to function as a multiple item search because they are only manipulating text entries in a single entry, which unless such a single entry is recorded in the database specifically, it won't otherwise come up even though separate entries would and or do so. Essentially, you are performing a specific search for all the terms provided as one string of text, not a general search for each term. So the syntax would need to be added to the social engine php search algorithm to be able to support separate search strings within a query so list boxes can be fully supported.
My site currently does not feature list boxes.

**Comment by Elshara** [comment] 2017-03-01 00:32
Whether or not it is an actual bug, or if it is a feature suggestion, relies on the intended use of how search ought to function within social engine.
I think it is both. A bug would imply search is not treating list boxes as a multi-string search query. whereas if say, you search in combination using other parameters, it is likely other parameters may interfere with the independent nature of how fields with multiple selectors function.
Currently fields with multiple selectors functions alright except for the list box, which is an outdated form of choosing. The modern standard is a combo box or radio button for single selection. A check box for both single and multiple selection. As well as multiple combo boxes for multiple selections if the data supports saving in such a way. Otherwise, it's essentially up to you how you wish to structure your data.
I don't think social engine supports multiple combo boxes at once per field entry nor does it support multiple check boxes at once per field entry. Which makes me believe this is more of a suggestion, than a bug, as the existing functionality doesn't yet exist for search to even build from.

**Comment by Elshara** [comment] 2017-03-01 00:33
I don't mean to burst your bubble, but until we know for sure. I suggest waiting until you hear back from an official developer about what type of issue this is, and if it will be fixed in another version. When ever it happens.

**Comment by poeticjustice** [comment] 2017-03-01 00:42
Social engine have confirmed to me in email that it is in fact a bug @elshara

**Comment by Elshara** [comment] 2017-03-01 02:18
See that's the stuff you don't see in git hub. Nice.

**Comment by poeticjustice** [comment] 2017-03-01 02:21
@Elshara yep, but i make sure to report in the public domain like here, so it can be seen, get others involve and update them, rather than being isolated via a ticket

**Comment by Elshara** [comment] 2017-03-01 04:14
You'd think they'd make their support a bit more readily available. I
kind of wish that could happen. I mean tickets are good for personal
issues, you want to talk privately specifically for such a reason. But
I just don't understand why a more free support experience isn't
available. This platform sure can be expensive if you don't know what
you're doing. IT used to be the case where nobody even had git hub. So
I'm glad we have it. So we can communicate without having to sign up
to a locked in forum I mean the way it is marketed sounds more like an
exclusive club rather than an inclusive interest. I also wish we had a
community entirely based on social engine php to talk about issues we
face and could also be duplicated as such.
I might even create one.

**Comment by DonnaScriptTechs** [comment] 2017-03-01 10:16
Hi @Elshara ,

We do have a free support area, our community :) . The reason our community is locked to those with a paid license (clients and developers) is to keep out spammers.

You are still welcome to go to my community for now, if you can't join our community.

**Comment by Elshara** [comment] 2017-03-01 11:42
It's also locked to people who use the free trial.

**Comment by DonnaScriptTechs** [comment] 2017-03-01 13:53
Yes as those are not clients yet. Once they are clients, they are able to use it. clients or developers. If you would like to discuss this more, please do contact us via our contact form or feel free to discuss with me at my forum so that we don't take this github issue off track as it slows our developers when they have to read a lot of extra stuff not pertaining to the bug itself. :)

**Comment by Elshara** [comment] 2017-03-01 21:10
Sorry about that.

**Comment by SpiritWolfie** [comment] 2017-03-07 22:34
Also can Confirm here at Furgather.

**Comment by DonnaScriptTechs** [comment] 2017-04-09 00:37
This is fixed for 4.9.0 when it is released. If you still have this issue after we release, please open a new bug report.

**Closed by DonnaScriptTechs** 2017-04-09 00:37 UTC
Labels: Bug

**Comment by Elshara** [comment] 2017-04-10 22:08
Awesome!

**Comment by poeticjustice** [comment] 2017-04-10 22:46
Truly hope this is fixed, because i will kiss @DonnaScriptTechs if it is hahahaha
