### ISSUE TITLE
base.js error

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#759] opened 2017-06-07 08:02 UTC
This issue has come back and seems to be intermittent, I've spoken to my plugin folks and they swear this isn't caused by them as they claim they don't use that kind of code etc.

Which leads me to believe its a issue with core SE...

TypeError: Cannot read property 'prototype' of undefined
&nbsp;https://www.youtube.com/yts/jsbin/player-vflZ_L_3c/en_US/base.js:30

This is part of the error I get, its something to do with the jsbin/player for youtube.

The full error is 

`
base.js:30 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.g.p (base.js:30)
    at remote.js:79
    at remote.js:162
g.p @ base.js:30
(anonymous) @ remote.js:79
(anonymous) @ remote.js:162`

It causes the inspect - console menu to crash consistently, If I disable all my plugs I still get this issue, It will sometimes go away and lots of youtube videos will not cause it, Then randomly it'll come back.

Further research shows it happens on Members/home/

Here is a screenshot
![image](https://user-images.githubusercontent.com/9712738/26868177-ec08bd66-4b1c-11e7-8e12-d93903737ccb.png)

And another

![image](https://user-images.githubusercontent.com/9712738/26868190-f45ea994-4b1c-11e7-8cc5-b8b85c7a2c93.png)

It keeps counting this error up massively, which causes the site to slow down, to refuse to load fully among other things, as well as crashing the console making you have to fully close your browser and reopen it.

**Comment by DonnaScriptTechs** [comment] 2017-06-07 09:52
Can you let us know if you are using Chrome? Researching this, the issue is reported to Chrome as a bug in their version but I will test this on Chrome 59.

**Comment by SpiritWolfie** [comment] 2017-06-07 10:08
Yes I am using chrome, its causing serious issues and seems to only happen on my website but not on youtube etc.

**Comment by DonnaScriptTechs** [comment] 2017-06-07 10:09
Are you on Chrome 59? It should be fixed in that as the bug with chrome itself is said to be fixed. The issue is not reported at youtube itself from what I've seen so that wouldn't be an issue there.

**Comment by SpiritWolfie** [comment] 2017-06-07 10:12
Using Version 59.0.3071.86 (Official Build) (64-bit)

As I said, Its not happening anywhere else except with social engine software from my testing, I don't see this error on any other websites, I am very curious if it might be one of your guy's cores things to do with jsbin

**Comment by DonnaScriptTechs** [comment] 2017-06-07 10:12
I'll test it when I start working.

**Comment by SpiritWolfie** [comment] 2017-06-07 10:15
Thanks. I did update to P1 of the new SE maybe that might fixed it, i'll check.

**Comment by SpiritWolfie** [comment] 2017-06-07 10:16
Here's something interesting, If a Youtube link is not on the feed the error does not appear, if I scroll down and Inspect near a youtube video appears, the errors appear, I'll get a video of it shortly.

**Comment by DonnaScriptTechs** [comment] 2017-06-07 17:04
Sorry for the delay. I will test this now.

**Comment by DonnaScriptTechs** [comment] 2017-06-07 17:10
I can't reproduce it on my site. I've tried a few videos in the main activity feed. I posted them in the feed. I'll go try posting them in the video section and then checking the main feed just to see if I can get the error to show. I also don't see it at our demo.

**Comment by SpiritWolfie** [comment] 2017-06-07 23:04
I'm making a video, I've tested this extensively and had other devs test it as well, According to them its happening with the embed with Iframes

I'll be sending you a video link with a photo, showing the testing i've done, and a interesting finding I found etc... I'll send this to you on your website because it shows allot of my users names and I want to respect their privacy and not post it in a public space.

**Comment by SpiritWolfie** [comment] 2017-06-07 23:29
I sent it to you Donna.

**Comment by DonnaScriptTechs** [comment] 2017-06-08 10:34
base.js is from youtube itself when using the embed. I'm still trying to reproduce the issue. I did see your video. I noticed that you mentioned on a development site with no plugins that it worked there. Can you test there again?

**Comment by SpiritWolfie** [comment] 2017-06-08 18:18
base.js is not from youtube.... 

Base.js. An expansion of John Resig's simple js classical inheritance that allows for developing classes using the module pattern, and also introduces a Scope object which is passed between links in the inheritance chain. It also refrains from using protected words.

https://www.npmjs.com/package/basejs

It is a function someone created that others can use for different reasons...

Outside of this, I can test this again on my demo site, 

Now I've already tested this extensively as is.... So if its not the addon folks, they say they don't even use that kind of code in any of their addons period, and its not SE, then who's error is this? As I can't reproduce this error anywhere across the net... I've spent all night checking countless other websites and platforms that handle Youtube weblink embedding 

Oxwall, Druple, facebook etc... are just some examples.

**Comment by shivani2910** [comment] 2017-06-09 11:57
Hi @SpiritWolfie,

I looked into the problem more and found this thread: https://productforums.google.com/forum/#!topic/youtube/MdzGvTDSSnM;context-place=forum/youtube

The error being discussed here is similar to what you've mentioned above. Here is the screenshot that one of the users has shared: https://lh3.googleusercontent.com/-E77mV80zNYs/WSsbXh0NpZI/AAAAAAAAE-w/voKqUtjnoQQObEgr_l3o3L8FnrdByPsbgCLcB/s1600/Capture4.PNG and mentioned:

```The problem is independent of the embedding websites since just opening a Youtube embed directly fills the console with errors at a rate of 500/second as shown in the screen shot.``` 

So, one thing is clear - The error is appearing randomly and has started appearing after YouTube made some updates at their end. So, this is not something that is happening because of any work done in SE PHP in last few upgrades.

On a separate note, in the iframely integration that we recently implemented, we simply used the API provided by Iframely for adding rich embeds but that does not affect the basic embedding feature that YouTube provides and was used by SocialEngine PHP before iframely integration.

So, this is something that Youtube will need to fix at their end and is not something that can be fixed from within SocialEngine PHP code.

Thanks

**Comment by SpiritWolfie** [comment] 2017-06-09 19:27
Shiv, which confuses me

I tested countless websites that embedd youtube links, and not a single website that I spent a entire day testing this on, has anything even remotely close to this, I can not reproduce this error anywhere else except with SE

Thats why I'm under the impression its a issue with Social engine and not visa versa... if it was a issue with embedd code or something from youtube, You would think that if I embedded the link in countless other platforms at least one of them would spit this error or at least a error close to it, but thats not the case...

it also wouldn't explain why Donna can have 20+ youtube links and not have this issue yet I do?

**Comment by SpiritWolfie** [comment] 2017-06-10 21:04
It may also have allot to do with the sheer number of people we have on our website too, something my server tech thought about.

**Comment by DonnaScriptTechs** [comment] 2017-06-13 09:57
We would need to check on your site via a support ticket if you have support access. We can't reproduce this for our tests and we've tried. If you don't want to get paid support, you could try cloning your main site to your development site and then removing all third party plugins and themes and also any customizations and see if you can still reproduce it there. If not, you could add back one plugin or theme at a time and see which one breaks it.

**Comment by DonnaScriptTechs** [comment] 2017-06-18 10:29
I am finally able to reproduce this. It takes a while. I had left the videos on my live site and now the error shows and takes forever for the member home page to load, with only a few videos on that feed. We need to look into this more as many use Chrome.

I have two videos in my feed and the count for this error keeps going up, making my mac overwork. I am at 14765 now and it is rising.

**Comment by DonnaScriptTechs** [comment] 2017-07-03 13:52
I haven't been able to reproduce this since the last comment I made. Are you still having it?

**Comment by DonnaScriptTechs** [comment] 2017-07-03 18:18
We've added this to our list to fix . As this tracker is closing, we'll close this now. For new bugs, please post at our [new community](https://community.socialengine.com/forums/).

**Closed by DonnaScriptTechs** 2017-07-03 18:18 UTC
Labels: Bug
