### ISSUE TITLE
Members 3rd level profile fields missing on member profile page "Info" Tab

### ISSUE THREAD

**Issue by Vaibhavagarwal0807** [SocialEngine/phpv4-issues#517] opened 2016-12-07 06:25 UTC
Follow below steps to reproduce this issue:
-------------------------------------------
1. Go to Admin panel of your website.
2. Go to this link: SITENAME/admin/user/fields, click on Add Question Link >> select a question Type "Select Box" >> after enter choices by click on edit choices.
3. Click on any choice >> click on "add question" link >> select a question type "Select Box" >> after enter choices by click on edit choices.
4. After click on choices >> click on "add question" and create a "Single Checkbox" type question. Please follow below screenshot:

![admin_panel_profile_questions](https://cloud.githubusercontent.com/assets/11191902/20956928/ecd14eae-bc72-11e6-8c59-c9b5248ded87.png)

5. Now, you can sing - up on your website and fill above field in second step of signup. Please follow below screenshot:
![second_step_signup](https://cloud.githubusercontent.com/assets/11191902/20956936/fa737ef6-bc72-11e6-816b-d192467228b1.png)

What happens?
-------------
Now, you can go to Member Profile Page and click on info tab >> third level fields missing in this tab. Please follow below screenshot:
![memberprofile_info_tab](https://cloud.githubusercontent.com/assets/11191902/20957016/5e5839ac-bc73-11e6-9d8b-18faa93364b6.png)

What were you expecting to happen?
----------------------------------
Third member level filed show in info widget.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …

**SocialEngine PHP Version:**
4.8.12

**Comment by Elshara** [comment] 2016-12-07 14:21
Yeah there is some problems with profile questions displaying their view settings its not just that particular field. I can Confirm this.

**Comment by poeticjustice** [comment] 2016-12-07 15:35
How have i not noticed this before, I can 100% confirm this also @Vaibhavagarwal0807  @Elshara 
It also does it on 2nd level.

I replicated what you did and same result.

This i tried Select box first question, then 2nd level question checkbox, and it doesnt show the checkbox at all in the info section.

Then i tried single checkbox on its own at first level question, naming it confirm.

And it doesnt even show that on the profile at all.

So it seems single checkbox function is globally hidden

**Comment by Elshara** [comment] 2016-12-07 16:50
It is a bug.

**Comment by Khushboo016** [comment] 2016-12-13 07:28
Hi @Vaibhavagarwal0807 , @Elshara , @poeticjustice , We've this checked issue at our end and are able to reproduce this, so, we've added this in our internal bug tracker and will fix the same in near future release.

Thanks & Regards!

**Comment by Elshara** [comment] 2016-12-14 01:29
Thank you! Much appreciated.

**Comment by poeticjustice** [comment] 2017-01-22 03:32
Awesome but you need to added this bug I mentioned in post https://github.com/SocialEngine/phpv4-issues/issues/536

This is a really bad bug and causing issues

**Comment by JonSimon93** [comment] 2017-03-13 19:55
**Just found SE on github, previous i found help from users on SEF.
I had this issue, but no one on SEF could help. Has this been fixed in 4.8.13, I would rather not update unless it fixed this issue.
Also what is the difference between marking as bug and being added to Milestone?
Only as I do not see a bug tag.**

**Comment by Elshara** [comment] 2017-03-13 20:14
Welcome to the community.
The difference between a bug and a milestone is simple. Milestone
means it's considered for inclusion somewhere soon, but not a definite
soon. It's a way of prioritizing issues stated here. Bugs, are what
such issues are referred to, only the terms are interchangeable.
You wouldn't see a tag here necessarily labeled bug, because all
issues are labeled as such usually in its title. So therefore, you'd
only see specific information in the description if it is in fact, a
bug, or feature request.
Yes this feature will be fixed in the next update. So no worries.
Hope it helps. I've heard of SEF.

**Comment by JonSimon93** [comment] 2017-03-13 20:23
**thankyou @Elshara nice to have reply from someone at Social Engine, keep up great work team**

**Comment by Elshara** [comment] 2017-03-13 20:28
You're welcome. I'm happy to help.

**Comment by DonnaScriptTechs** [comment] 2017-04-10 20:56
This is fixed for 4.9.0 when it is released. If you still have this issue after we release, please open a new bug report.

**Closed by DonnaScriptTechs** 2017-04-10 20:56 UTC

**Comment by Elshara** [comment] 2017-04-10 21:49
Awesome!
