### ISSUE TITLE
Vertical Menu Not Responding Correctly

### ISSUE THREAD

**Issue by MDNobles** [SocialEngine/phpv4-issues#755] opened 2017-06-02 19:42 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
----------------------------------

Chrome: (Icon only)
When I hover over to the right of the menu the scroll bar momentarily appears and disappears after a few seconds. If I try to grab it with the mouse (before it vanishes) and try to pull it down it wont move...but, if I use my down arrow key it'll scroll down.  If I try to click below the scroll bar and attempt at bringing it down, it thinks I'm trying to click on a menu page and redirects.

Chrome: (Icon and Label)
No scroll bar and no way to get the menu to move down...even with the arrow key. 

Firefox: (Icon only)
When I hover over to the right of the menu the scroll bar momentarily appears and disappears after a few seconds. If I try to grab it with the mouse (before it vanishes) and try to pull it down it wont move. If I hover over the scroll bar and push the down arrow key, the label that pops up and the page scroll but not the menu.

Firefox: (Icon and Label)
No scroll bar and no way to get the menu to move down...even with the arrow key. 

What happens?
-------------
Unable to grab the menu scroll-bar and drag the menu.

What were you expecting to happen?
----------------------------------
I should be able to grab the menu scroll-bar and drag the menu up and down easily.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
Theme: Insignia Black v4.9.1

My Laptop's resolution is set at 1920 x 1080. I have extended my desktop to a second screen with the same resolution and the problem remains. Furthermore, I dropped my resolution to 1600 x 900 and 1024 x 768 on both the laptop and secondary screen and received the same results.

What versions of software are you using?
----------------------------------------
**Operating System:** The problem has been repeated by three of my laptops; Windows 8.1, 8.1 and 10, as well as a tech from TMDHosting.

Windows 8.1 (64-bit)
Chrome: Version 58.0.3029.110 (64-bit)
Firefox: Version 53.0.2

**SocialEngine PHP Version:** 4.9.2p1

**Comment by DonnaScriptTechs** [comment] 2017-06-03 13:45
Would you also please state the screen size as Ray had asked in the community?  It will help our technicians. Thank you!

**Comment by DonnaScriptTechs** [comment] 2017-06-08 08:40
Our team would like to see this on your site. Would you please send site details to support@socialengine.com ? Please include the details of what's happening so the tech that gets the ticket will know, and the github bug link.

**Comment by MDNobles** [comment] 2017-06-09 13:10
Done

**Comment by DonnaScriptTechs** [comment] 2017-06-09 13:15
Thank you. One of our technicians will have a look.

**Comment by DonnaScriptTechs** [comment] 2017-06-14 12:28
Did this get resolved in your ticket?

**Comment by MDNobles** [comment] 2017-06-14 12:38
Hi Donna,

No, it's still a work in progress.

Thanks,
MDNobles

On Jun 14, 2017 7:28 AM, "DonnaB" <notifications@github.com> wrote:

Did this get resolved in your ticket?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SocialEngine/phpv4-issues/issues/755#issuecomment-308415976>,
or mute the thread

**Comment by DonnaScriptTechs** [comment] 2017-06-14 12:39
Thank you for responding so quickly. I hope we can figure this out for you. :)

**Comment by DonnaScriptTechs** [comment] 2017-06-15 12:00
Our technicians can't reproduce this issue with various devices. We'll leave this open for now in case someone else comments here that they can reproduce it with 4.9.2p1 version (theme and core)

**Comment by MDNobles** [comment] 2017-06-16 05:52
I'm not sure why the SE technicians are unable to reproduce but, we can add SEAO (SocialEngineAddOns) to the list of those who can (hosting company and myself) reproduce the same results....

Hi Michael,

Greetings for the day!

1) "When I hover over to the right of the menu the scroll bar momentarily appears and disappears after a few seconds" >>

This is working fine on our end, Michael. We have created a video of this of Chrome and Firefox Browser for your reference. Please check them at your end and let us know if we have missed anything from our part here.

Video Links:

(Links provided privately to support if requested)

2) "No scroll bar and no way to get the menu to move down...even with the arrow key" >>

The issue we are facing here is that when we click on the scroll bar in the menu and scroll up and down, it does not work.

Please let us know if you are referring to the same issue here. If we have missed anything from our part here, let us know. We would be happy to help you.

Thanks & Regards,

Aashi
SocialEngineAddOns

**Comment by DonnaScriptTechs** [comment] 2017-06-16 09:02
How many menus do you have and I'll test again as I also could not reproduce it on win10 with latest browser versions or on macbook pro with latest browsers.

**Comment by DonnaScriptTechs** [comment] 2017-06-16 09:02
Do you have a video of it? You can send it to me on scripttechs so you don't post any sensitive stuff here such as user profiles and stuff.

**Comment by DonnaScriptTechs** [comment] 2017-06-16 09:59
Ok we see the issue now and will improve it. Will move this to feature requests as it's an enhancement. Thank you for sticking in there with us to figure this out.

**Comment by DonnaScriptTechs** [comment] 2017-06-16 10:00
This issue was moved to SocialEngine/phpv4-feature-requests#124

**Closed by DonnaScriptTechs** 2017-06-16 10:00 UTC
