### ISSUE TITLE
Bug - Broken links

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#419] opened 2016-05-12 01:59 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)
## What are the steps to reproduce this issue?
1. …Go to SE Default forums and make a post
2. …Copy the url
3. …Paste the URL into the activity wall
## What happens?

…you get a 404 error
## What were you expecting to happen?

… For it to link correctly
## Any logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
404 - Not Found
```
## What versions of software are you using?

**Operating System:** … Windows 10

**SocialEngine PHP Version:** …Latest

"other comments

The link works fine! it just displays as a 404 - Not Found but is still fully functional when clicked on
This also happens when you try to link to other areas of the site, some link just fine others give the 404 and wont link correctly while others give 404 and will still function correctly

Also please don't tell me its a issue with my server box or my configuration, I have tested this problem multiple times Including on a different server, and on fresh installs of SE. I'm attaching a image, and please please don't tell me this works fine on your guy's end, I'm not sure if your testing this stuff on cloud or the php fox, but I have tested this countless times on multiple fresh installs and different server installs it happens every time.

**Comment by SpiritWolfie** [comment] 2016-05-12 02:02
I have no clue why its code snipping I've tried to fix it so it doesn't and tried to make the link clickable but no go.

**Comment by SpiritWolfie** [comment] 2016-05-12 03:00
something else thats related to this issue, normal linking breaks

Here's another pic

![capture](https://cloud.githubusercontent.com/assets/9712738/15202878/0cc535a0-17b3-11e6-96b2-831c5d08bcde.JPG)

**Comment by SpiritWolfie** [comment] 2016-05-12 03:03
here's the first image since it refuses to not put my comments in a none code box

![404 error](https://cloud.githubusercontent.com/assets/9712738/15202888/274727a8-17b3-11e6-9f68-b0e82b7c188d.jpg)

**Comment by Elshara** [comment] 2016-05-12 12:06
Links just show code anyways in my experience every time they are mentioned in SE. Especially when viewing status updates. They don't link at all it's just a mess of code. The problem is with the editor of the activity feed itself. I say this over and over again, we must have a consistent text editor for anything to reference itself properly and pull in data through an embed service. Be it links, videos, images or other external content and yes I'm referring to RSS feeds here. The links module never worked properly in SE.

**Comment by Khushboo016** [comment] 2016-05-13 08:01
Hi @SpiritWolfie , @Elshara , The issue that you've mentioned here that the links created are not working fine, this is not reproducing at our end. We've also checked this issue on the demo site of SocialEngine, we posted a topic "Test Topic" in the Forums module and copied its URL and then posted that as a link through Activity Feed on the Members Home Page, and found the link created working fine and not giving any 404 eror. You can also check that link created from https://demo.socialengine.com/members/home ,you can use the below login details:
Email Address: bellawatsonxyz@gmail.com
Password: testuser
Or you can also create a test account of your own on the demo site to check this issue. So, we suggest you that if you do not face this issue on demo site but still face it on your installation, so you can open a support ticket for the same at https://www.socialengine.com/client/ticket/create or you can email us at support@socialengine.com along with your site FTP details, so we can check this issue.

**Comment by SpiritWolfie** [comment] 2016-05-13 22:12
Don't close this yet please I'd really hate to find out it is a issue with social engine then have to remake this, I'm going to test this right now.

**Comment by SpiritWolfie** [comment] 2016-05-13 22:30
Confirmed, happens on your Demo site, as for the 404 problem it's certain things that causes it, is there anyway for me to grab any kind of more useful info?

Could you guys in the future test this stuff a bit more throughly, I think you guys don't test some of the things we mention correctly, I'm not trying to be rude here, but every single time I've brought up any issue I basically get told its my server or somethings wrong with my installation, or I'm confused about what I'm talking about >.< I test this stuff extremely well before I bring it up, I'm a lead bug tester for 7cups of tea and Delrict gaming,so I know a bit about bug finding....

Like for example I reported that every-time I've tried to install a fresh copy of social engine I have to modify the **.htaccess file**, I get told its a problem with my server configuration/setup, so I change servers completely, different OS the whole 9yards, Get the same issue, try another configuration/setup following the Guide, SAME issue. even your guy's Video installation tutorial states its a 'common issue' with installing social engine. As seen here in your guy's video - https://youtu.be/P-gUEzsesjU?t=82 he says 'its a common issue' it starts a few seconds after the time I captured.

![untitled](https://cloud.githubusercontent.com/assets/9712738/15263427/b99e41ba-191e-11e6-8903-e6f7ec56468f.jpg)

**Comment by Elshara** [comment] 2016-05-13 22:35
Issue verified here on my end.

**Comment by SpiritWolfie** [comment] 2016-05-14 00:09
here's the 404 error with inspect
not sure if this will be helpful, but I think its tied into the above issue some-how.

![404 error with inspect](https://cloud.githubusercontent.com/assets/9712738/15264867/5ecef96e-192d-11e6-9ffa-7bd418b7348b.jpg)

**Comment by Elshara** [comment] 2016-05-14 00:53
Inspect shows a ton of errors besides this one.
Fire bug via fire -fox.

**Comment by alimoosavi15** [comment] 2016-05-14 02:16
@SpiritWolfie The issue is happening in a 3rd party plugin ( Advanced Activity Feed ) you're using for your news feed. This is not a SocialEngine product so you'll need to contact the vendor of that plugin.

**Comment by SpiritWolfie** [comment] 2016-05-14 02:19
Alimo, Incorrect, It happens on their default wall feed, as seen in one of the picture's I've provided, which I tested the issue on their demo site and got link breakage there as well, To reproduce the 404 error without the plugin I'd have to find which urls causes it, but its not a issue with advance wall feed, Advance wall feed uses allot of the functionality from the default Wall feed so it pulls allot of its info from that hench why the issue happens with it installed and without it installed

Take a look at my screenshot from 4hours ago, that is their demo site where the issue is happening I was able to reproduce the issue in barely a min.

**Comment by alimoosavi15** [comment] 2016-05-14 02:26
I tried the demo and my local setup and I was not able to reproduce this issue.

**Comment by SpiritWolfie** [comment] 2016-05-14 02:27
It seems to happen if you put text first then link at bottom, and from rare occasions when just linking normally without any additional text, its a intermittent issue

Here is what i've gathered poking around firebug some more

<span class="feed_item_posted">
<a class="feed_item_username" href="/profile/bella">Bella Watson</a>
<span class="feed_item_bodytext">
<a rel="nofollow" target="_blank" href="http://i">http://i</a>
.imgur.com/qx4civl.png
</span>
</span>

Take a look href it puts i">then http while I don't know much about html but this may be something useful.

**Comment by SpiritWolfie** [comment] 2016-05-14 02:29
@alimoosavi15 because your not testing it correctly... 

Copy and paste this into their demo site

but here is what i was tryng to say. to have the caption placed under the pic (or even one line of the caption and then a read more)
http://i.imgur.com/qx4civl.png

**Comment by alimoosavi15** [comment] 2016-05-14 02:31
[Not happening](https://demo.socialengine.com)
![socialengine demo member home page](https://cloud.githubusercontent.com/assets/1803197/15265719/3ae26ef0-1941-11e6-9595-494abde2f160.png)

**Comment by SpiritWolfie** [comment] 2016-05-14 02:31
Re-check the newest post, as I just said It's a intermittent issue! Check with Firebug!

**Comment by alimoosavi15** [comment] 2016-05-14 02:37
Can you record a video?

**Comment by SpiritWolfie** [comment] 2016-05-14 02:38
@alimoosavi15  *sighs* I'd rather not do more labor then needed, I've already added a Site view with Firebug snapped to the right of the pic, to do a video I'd have to find some free video recording software and set it up and everything else, while still trying to work on my site.

**Comment by SpiritWolfie** [comment] 2016-05-14 02:40
FOUND IT

@alimoosavi15 on the post you made where it didn't break, open up firebug or inspect (preferably firebug) check the `<a rel="nofollow" target="_blank" href="http://i.imgur.com/qx4civl.png">http://i.imgur.com/qx4civl.png</a>`

Then look at the posts I made where it broke you get `<a rel="nofollow" target="_blank" href="http://i">http://i</a>
.imgur.com/qx4civl.png
</span>`

**Comment by alimoosavi15** [comment] 2016-05-14 02:44
Firebug is showing the aftermath. Inspecting DOM is not helpful in this case.

**Comment by SpiritWolfie** [comment] 2016-05-14 02:45
@alimoosavi15  did you see my above post with the code snippets? I checked the same div each time and got different results on the one where it didn't break vs the one where it did, It has to be something to do with the way its handling urls, perhaps its not clean posting the urls? I'm not sure.

**Comment by SpiritWolfie** [comment] 2016-05-14 03:00
Here's another test this time on Firefox instead of chrome.

![more tests](https://cloud.githubusercontent.com/assets/9712738/15265851/58c28f6e-1945-11e6-93d5-3aa1ee576b4a.jpg)

**Comment by Elshara** [comment] 2016-05-14 04:34
Links break when not rendered properly in html. Social engine could
fix this issue by simply rendering full html in a custom html editor.

**Comment by alimoosavi15** [comment] 2016-05-14 05:11
When copying that text into textarea, Are you copying a text with a broken link?

**Comment by SpiritWolfie** [comment] 2016-05-14 05:13
@alimoosavi15 no nothing is being copied with a broken link, The screenshots show that, you can see the above screenshot and see their is no space or anything in the link and its the same link as the one you posted.

**Comment by Elshara** [comment] 2016-05-14 05:32
When links are copied, they are copied as is usually as a stand alone
text field within a given status update prompt. If not they appear
after a space of existing text.

**Comment by smazurov** [comment] 2016-05-14 06:06
The highlight part is just "copy with styles" that TinyMCE can do. If you hold "Shift" while pasting (or right click, paste without styles) the highlight disappears. It shouldn't affect it. My guess is copy/pasting breaks it due to there being a space, but its hidden due to style thats copied with it. 

As far as I can tell there is no bug.

**Comment by SpiritWolfie** [comment] 2016-05-14 06:08
I right clicked and pasted and it breaks intermittently. I believe this may also be the cause of my 404 errors or has something to do with it.

**Comment by smazurov** [comment] 2016-05-14 06:11
Myself @alimoosavi15 and @Khushboo016 all tried to do it multiple times and were unable to make it fail. Not sure how else we can help unless you can provide some reproducible steps. If one of us could reproduce it, even if its intermittent, then we could determine a cause, otherwise I'm sorry we can't help further.

**Comment by SpiritWolfie** [comment] 2016-05-14 06:15
@smazurov 
All I'm doing is copying a post made on my website and pasting it into your demo site, that alone causes the break.

**Comment by smazurov** [comment] 2016-05-14 06:15
does it break if you paste holding shift?

**Comment by SpiritWolfie** [comment] 2016-05-14 06:18
@smazurov  I haven't tested that

But this issue is just one of the many issues i've had with social engine since buying it, I would love to help you guys bug test it if you have a volunteer bug testing team, because all these issues i'm running into is driving me batty, I've been involved in many bug testing teams for years now.

**Comment by smazurov** [comment] 2016-05-14 06:20
> But this issue is just one of the many issues i've had with social engine since buying it, I would love to help you guys bug test it if you have a volunteer bug testing team

Yes! You're part of it by creating this issue! More are always welcome, please use search to ensure the issue hasn't been reported in the past.

**Comment by SpiritWolfie** [comment] 2016-05-14 06:21
@smazurov  every time I have mentioned anything one of your other team members just tells me theirs a issue with my install/or server configuration and just closes my thread every single time.. (I know the team member who does it but I don't want to point fingers)

I want to help you guys more and perhaps even offer suggestions to make things easier cause as it stands my personal coder wants to code me a platform from the ground up because of how much of a nightmare social engine is/being and I want to help you guys by offering my expertise in different fields, Freely at that.

**Comment by Elshara** [comment] 2016-05-14 06:32
Links should be a separate module from activity feed. It's almost
impossible to moderate them otherwise one has to delete the entire
status update. If links and embeds were their own modules, there'd be
no issue. Custom html could appear as an embed type post.

**Comment by alimoosavi15** [comment] 2016-05-14 06:57
> as it stands my personal coder wants to code me a platform from the ground up because of how much of a nightmare social engine is/being.

@SpiritWolfie SocialEngine is based on Zend Framework. It's a complex and advanced framework and it has a steep learning curve. My advice, find a Zend or SocialEngine developer.

**Comment by Elshara** [comment] 2016-05-14 07:02
I do find zend to be reliable more so than smarty or laravel. Not so
much in terms of speed, but in terms of functionality if you code it
right. But one wrong move and the whole code could break. I just wish
that part of zend was not so strict in terms of still allowing the
site to run. As in the case of depricated css and php7.

**Comment by SpiritWolfie** [comment] 2016-05-14 07:09
@alimoosavi15 and pay 300$ dollars which is what I paid for this Software which doesn't even have the most basic functionality such as a working block feature which almost every Social networking platform out there has working (Even open source ones) or global permissions such as ability to set all your stuff to not allow none registered users to view content, (without having to go one by one per public role page and setting it by hand over and over and over again)

The cost of Social engine for starter is 300, the average cost of plugins is 40-45 from their store the cost for most average plugins run 25-60 , the cost to get something fixed that should be working in base is over 300+ Dollars (I've already got a quote)

I'd rather have my room-mate design me a platform from the ground up from that point, I know he can code, I've seen his work before and he's coded me websites in the past, 

The point is I want to help make social engine better  because I purchased it, theirs allot of areas social engine could be improved upon such as back end, global permissions, the editor, blocking, ability to edit comments on post the OP and responses.  Easier to use Layout editor or at least previews to see exactly which pages it's messing with

Or when adding say different genders to peoples profile questions after x amount of numbers it starts wigging out, things like that could be fixed, Finding another developer to fix the base issues of social engine isn't really their job, they didn't build Social engine, Social engines team did.

So suggesting I find another zend/ or developer to fix base issues with the software I bought is kinda eh... Considering I've not only bought a lincs, but I've also purchased multiple independit plugins from their store page (not third party) and had issues with those even!, Such as chat not being visible..

These are just a few issues of the frustrations I've ran into, Let not even talk about its virtually impossible to install social engine without having to modify their own files, I among others have repeatedly brought up this issue as well, That is not some other developers problem to fix, nor should I be required to hire someone to fix this issue so I don't have to keep modifying it every-time I want to install a fresh copy for testing purposes.

So please don't suggest I pay for more stuff, after the sheer amount of money I and many others have invested into this product. 

Thank you
~Spirit

**Comment by Elshara** [comment] 2016-05-14 07:20
That's why we're here to resolve such issues. honestly if this git hub
page didn't exist before now, I wouldn't have found you.
Social engine has been around a long time and such issues may be years
old. Which only now have come to the surface because of new owners.

**Comment by SpiritWolfie** [comment] 2016-05-14 07:22
My Offer!
if someone want's to set up a base install of Social engine fresh, with all the modules offered by social engine and pass me admin rights with a username and password, I will personally personally go though it and find what breaks how it breaks and make a archive/ even video recordings if I have to

I will do this at no charge if people just take the issues I find a bit more serious.. 

Please let me know if you'd like to take this offer up, and I'll get to work once I can get access to a platform I can mess around, this way I don't have to harass my server tech to install another fresh dev copy and modify files to fix the problem just to get it to install.

**Comment by alimoosavi15** [comment] 2016-05-14 07:29
I install multiple instances of SE every week and I've never modified any files during the installations. The only step with the files is setting the permissions which is a common step in installing most if not all CMSes.

Regarding my earlier advice, I wasn't aware of your pro bono arrangements between you and your coder.

**Comment by SpiritWolfie** [comment] 2016-05-14 07:35
@alimoosavi15  Pro- bono? I don't believe I mentioned it being free..... Please don't assume...

Secondly, it's mentioned right here in their own video - https://youtu.be/P-gUEzsesjU?t=82 I time captured it, a few seconds after the time I have captured it talks about having to edit .htaccess and such and how it's a "Common issue", I don't remember how we fixed our installation issue but it happens everytime on both of my personal server boxes which I have physical access too and own.

It also happens on my friends servers which I've installed my copy over there as well, and Elshara has also ran into this issue, and so has the person over at ExCreator, in-fact he's wrote a thing about it here 

https://excreators.com/community/forums/topic/81/social-engine-installation-500-internal-server-error-solved

Which is followed with - http://support.socialengine.com/php/customer/portal/articles/1667583-installing-socialengine?_ga=1.147731828.233239993.1450705102 if you take the time to watch the video they link too, it mentions this issue as a "common problem", So I'm not sure why it's working for you, but once again I have tested this countless times and run into each time, By default my server box meets SE requirements without any changes and once we get past the installation issue, the check boxes are pretty much green across the board.

**Comment by SpiritWolfie** [comment] 2016-05-14 07:38
We've completely derailed this thread...

My offer stands if someone wants to set up a base install untouched and pass me some admin rights I'll find what breaks and make a list, I do allot of professional testing for people free all the time, such as 7cups of tea, delerict gaming and many other places, I simply want to help find these issues and get them resolved so everyone can enjoy the platform they purchased.

With that lets not cont any further arguing as its really starting to get to me etc...

**Comment by alimoosavi15** [comment] 2016-05-14 07:55
I apologize for giving an advice and assuming you're either paying or not paying for a coder :)

**Comment by SpiritWolfie** [comment] 2016-05-14 07:58
@alimoosavi15  it wasn't the advice that set me off

Thank you for apologizing though the reason to why it set me off was because it came off as "Pay someone else to fix social engines base issues" after I've invested so much time and money and resources into trying to figure these issues out.. that's just sorta how it came across to me, if thats not how you intended it then I'm sorry for mis-reading, I'm just a bit touchy because even on a fresh install I run into countless issues without anything added.

(also did you check out the video I linked)

**Comment by smazurov** [comment] 2016-05-18 00:21
> does it break if you paste holding shift? Or if you paste without style, does it add a space?

@SpiritWolfie can you confirm this?

**Comment by SpiritWolfie** [comment] 2016-05-18 00:23
@smazurov let me test that now.

**Comment by SpiritWolfie** [comment] 2016-05-18 00:30
@smazurov 

Yes it still add's the random space in the href code and in the url after its pasted even if I shift paste, would you like me to make a video?

**Comment by smazurov** [comment] 2016-05-18 00:35
If I understand you correctly, that means that the source of where you're copying from has that space - its not something we can easily address. If that happens with every link you're trying to paste then the issue is most likely with your browser. 

One last test: If you were to paste into notepad (or any editor that does not take rich formatted text, like sublime text or notepad++), and there is a space, then the issue is definitely with the source material you're copying. Otherwise, what is your browser and Browser version? I'm assuming you're on windows 10.

**Comment by SpiritWolfie** [comment] 2016-05-18 00:48
@smazurov 

![image](https://cloud.githubusercontent.com/assets/9712738/15344015/4beefcfe-1c57-11e6-9a9f-8b716ad5b60a.png)

No spaces in the url before I paste it, I checked the demo site too when I paste it and there is no space

this is from the demo site even when I shift paste 

I have tested this on facebooks wall, Oxwall , dolphin, druple, and can not get this to happen on any of them, in-fact it clean catches the info every time, no black highlights nothing.

![image](https://cloud.githubusercontent.com/assets/9712738/15344031/814f76c6-1c57-11e6-964a-9375da320aee.png)

**Comment by SpiritWolfie** [comment] 2016-05-18 00:49
Forgot to close my tabs sorry x.x

**Comment by smazurov** [comment] 2016-05-18 00:51
I think I have enough info. No promises on the timeframe, but we'll address it. Thanks for your report.

**Comment by SpiritWolfie** [comment] 2016-05-18 00:56
@smazurov Thank you so much

From what I can understand while I may not know to much about this stuff but I think it has allot to do with how the default activity wall handles url grabbing, when I compare firebug on facebook or oxwall and such I noticed that no matter how I cross paste something the code on the href tags have no spaces or such and it just clean pastes the url every time

So I think it's something to do with that area while I could be wrong, and I also believe (Could be wrong here too) That this is also related to the 404 error issue I'm getting, I think its not linking the posts url correctly

once again thank you!

(on a side note, any info on the newest update for social engine or anywhere I can look in regards to the process on that?)

**Comment by SpiritWolfie** [comment] 2016-05-18 00:58
@smazurov 
Sorry for the double mention I just noticed the question above

Otherwise, what is your browser and Browser version? I'm assuming you're on windows 10.

yes windows 10, tested on 7 as well, Tested on chrome, Firefox and Microsoft edge, same results.

**Comment by DonnaScriptTechs** [comment] 2017-02-08 16:35
Is there an update on progress on this for the client please?

**Comment by SpiritWolfie** [comment] 2017-02-08 21:42
@DonnaScriptTechs 

I believe this will be fixed in 4.9 as 4.9 is moving its url grabbing stuff to Iframely

**Comment by Khushboo016** [comment] 2017-02-09 12:35
Yes, this issue of broken links formed is going to be fixed in upcoming release 4.9.

**Comment by DonnaScriptTechs** [comment] 2017-04-04 16:45
This is fixed for 4.9 when it is released.

**Closed by DonnaScriptTechs** 2017-04-04 16:45 UTC
Labels: bug

**Comment by Elshara** [comment] 2017-04-05 06:51
Awesome.
