### ISSUE TITLE
Feature Request - fontawesome profile signup questions, and shown on members info section

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#709] opened 2017-04-25 01:36 UTC
@Jonsimon93 mocked the image up below.

But now SE 4.9 has added fontawesome support to menus and across the site.
Please offer ability to add profile questions to have a font awesome icon, and its Div to be before the question

![e518a666-092b-11e7-9715-0d3e67b752b8](https://cloud.githubusercontent.com/assets/19233272/25365305/ab4f3d74-295f-11e7-9526-d11d6f465b67.jpg)

**Comment by Elshara** [comment] 2017-04-25 07:59
Icons in social engine don't work right anyways. What ever they are
made with, it isn't font awesome.

**Comment by DonnaScriptTechs** [comment] 2017-04-26 10:47
duplicate of #595

**Closed by DonnaScriptTechs** 2017-04-26 10:47 UTC

**Comment by Elshara** [comment] 2017-04-26 22:21
That's what I thought.

**Comment by poeticjustice** [comment] 2017-04-26 22:49
appolgise is was a duplicate @DonnaScriptTechs 

I only raised again as I loved the idea and never saw any action or comments regarding this.

As you made a comment "We do have font-awesome coming in 4.9 :) . I've not checked to see if it's in any of the profile areas."

I felt like If any other team members saw the post, they would see your reply and think 
"ohhhh its a font awesome request, yea its coming"

We dont know if its being considered or put to the team for thoughts.

Then with release of 4.9, it kinda copy buried with no reply for the team, thats why raised again, but obviously this is closed now, therefor its never gunna be tracked or thought about

**Comment by DonnaScriptTechs** [comment] 2017-04-26 22:52
No problem. Note that the issue I linked is open and is for this same request so it's not a lost cause. We just need to close duplicate requests to try to keep the tracker sorted out. :)

**Comment by poeticjustice** [comment] 2017-04-26 23:17
:) @DonnaScriptTechs  Im just passionate about SE, esp as I want to buy 5 more licences, but it all depends on one section of SE if i remain or move.

**Comment by DonnaScriptTechs** [comment] 2017-04-27 10:25
Feel free to pm me at the community and let me know there which section you mean. Thank you :)

**Comment by poeticjustice** [comment] 2017-04-27 13:29
@DonnaScriptTechs done

**Comment by Elshara** [comment] 2017-04-29 14:08
I should probably check out the community, I did join. Is it active?
