### ISSUE TITLE
Blocking doesn't work correctly.

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#756] opened 2017-06-06 05:07 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …Block someone
2. …have block person post on a post on global feed
3. …

What happens?
-------------
…You can see their responses etc, according to patch notes this was suppose to working correctly..

User A Who blocks User B should not see User B's stuff period
Users should also be able to block people who set their accounts to private as it stands the block button is not there.

What were you expecting to happen?
----------------------------------
… I expect the block to work correctly, if you block Person A, You shouldn't see their stuff, Period. This is not the case.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…Please issue a fix for this as this is a MAJOR issue that allot of us honestly need fixed asap....

What versions of software are you using?
----------------------------------------
**Operating System:** …

**SocialEngine PHP Version:** …

**Comment by DonnaScriptTechs** [comment] 2017-06-06 09:47
I tested this on my 4.9.2 site.

User A and User B are friends.
User B posts a photo in the main feed.
User A sees it and then blocks User B.
The photo that User B had posted has disappeared and I don't see it in the feed.
Since a block is 2 way, User B can't see any of the feeds from User A now either.

Please provide more testing details as feeds are working fine for me.

For private profiles, those are unable to be viewed. We should add a "Block Member" to the member browse page under or next to the Add Friend/Remove Friend button. I'll add this part to our internal improvement list.

**Comment by SpiritWolfie** [comment] 2017-06-06 20:47
From what I understand how we have our website is different then yours, which could be the reason to why your not able to reproduce this atm

Set the website to be global on the wall feed (no need to be friends to chat with each other)

have 3 accounts able to test this...

First things, Make sure no one is friends on these 3 accounts

Step 1: User B Post a thread on the global wall feed.
Step 2: Have User A block user C (don't do it for both )
Step 3: Have User C Comment on B's Post
Step 4: Have User A Check B's Thread, You should be able to see the block persons post etc.

You will notice you can view said comment, This should not be the case.

**Comment by DonnaScriptTechs** [comment] 2017-06-06 21:39
I'll test again as the site is set up as global. Will test when I work tomorrow.

**Comment by SpiritWolfie** [comment] 2017-06-06 21:40
your site is set up as global? cause you mentioned 'friend of friend' which is the default set up for Social engine, that requires you to send a request and they must approve it to see their posts on /home/ 

(which is basically facebook)

ours is set up everyone can talk on /home/ regardless of connection/friend

**Comment by DonnaScriptTechs** [comment] 2017-06-06 21:52
I mentioned user a and b are friends. Not friend of friend. :)

It's set up the default way.

<img width="594" alt="feed" src="https://user-images.githubusercontent.com/6908282/26853655-e164fb36-4ae0-11e7-8f7d-d7bc0e0044d7.png">

**Comment by SpiritWolfie** [comment] 2017-06-06 22:09
Alright just making sure, I mis-read my bad.

but ya I've tested this on my live and dev and I get the same results, we can see other peoples posts. when they are blocked.

**Comment by SpiritWolfie** [comment] 2017-06-07 04:08
Actually this may be a issue with the mobile aspect, From what I'm gathering from my users, This is a issue if your using mobile you can see their posts. Sorry for the confusion.

**Comment by DonnaScriptTechs** [comment] 2017-06-07 17:35
I can reproduce this and will mark it a bug. I am not a core developer to know how this was designed. I'll add this to our internal list to check and a core developer can determine if it is working as intended, needs fixing, or needs improvement.

**Comment by SpiritWolfie** [comment] 2017-06-07 22:19
Donna, if they say this is working as intended, I'm going to flip, In no right mind would this be classified as 'working as intended' in any ones eyes

Blocking is meant to block people from seeing you what you do, by having it working one way and not 'global' as we've been asking for it allows users to bypass the block, Not everyone is going to get along, but that doesn't mean these people are breaking site rules ToS, we encourage users to block those they simply just don't like etc to avoid personal conflicts....

It should not 'only work' if you are a friend of said person - then block them

it should work "period" If I block user B they are blocked, regardless if I was friends with them or not, This is a issue that has been complained about since I first purchased my platform, I had over 40+ People (and now climbing drastically since my latest influx) Complaining about this not working, (it's also pretty buggy with mobile as well just a headsup.)

**Comment by DonnaScriptTechs** [comment] 2017-07-03 18:19
We've added this to our list to fix . As this tracker is closing, we'll close this now. For new bugs, please post at our [new community](https://community.socialengine.com/forums/).

**Closed by DonnaScriptTechs** 2017-07-03 18:19 UTC
Labels: Bug
