### ISSUE TITLE
Music Problems

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#197] opened 2015-07-26 23:43 UTC
When someone posts new music, and their profile playlist is titled something that another members profile playlist is already using, it hides anyone else who has their albums displayed as that title. This is most commonly noticed under the name profile playlist and the only way to have a member view their own profile playlist is through the actual admin panel specifying it by id. They cannot add songs to it because another member is using the same title.

**Comment by Anshuse** [comment] 2015-08-14 13:18
Hi @Elshara , we're not able to reproduce this issue at our end.

**Comment by Elshara** [comment] 2015-08-14 17:12
Interesting. Thing is, their own playlist displays on their profile,
but it doesn't in browse music area.

**Comment by Anshuse** [comment] 2015-08-17 06:59
Hi @Elshara , we've checked this issue again by following below steps:

1) Logged in as Testuser1 and uploaded a music with title "Test1".
2) Logged in as Testuser2 and uploaded a music with title "Test1".

Now, when we go to "Browse Music" section then both of the music files with same title "Test1" are being displayed there. Now, as we're not able to reproduce this issue at our end so, we're closing this one.

Thanks!

**Closed by Anshuse** 2015-08-17 06:59 UTC

**Comment by Elshara** [comment] 2015-08-17 07:18
Thanks.
