### ISSUE TITLE
Pre-Launch SE 4.9 email, but what enhancements? and suggestions.

### ISSUE THREAD

**Issue by JonSimon93** [SocialEngine/phpv4-issues#596] opened 2017-03-14 18:54 UTC
Hi All 

Im new to github, i have worked on my friends Social Engine, helping him over the years.
I did have a SE demo also some time ago, and joined github yesterday after receiving the pre-release discount 4.9 email.

Im at the point of wanting to buy the top package now. as i have seen more 3rd party dev make some sweeeeeet plugins, But before buying i want to see the commitment to keeping this fresh and up to date.

1/ There needs to be instagrm and other specific questions, or even use of the website question, where in the profile questions, admin can pre define the weblink
So adding website question, admin can add www.instagram.com/ then the field for the user can just input the user ID.
2/ Gifs, these are my fave things on facebook, i dont even reply with words, i simply use gifs for replies, because its funny.
3/ Better HTML editor, sometimes the html does not work properly
4/ Better sign up process, ability to span signup over multiple pages based on questions asked, just so it can be broken up..... I found on other sites, having a long one page signup causes users to drop off from the site with intention of doing when not busy, but they easily forget to do it later..... but spanning it accross pages, once people commit, there subconscious tells them to see it to the end.... so a continue to next page for the form filling would be sweeeeet.
5/ Different homepage and or profile page for prfile types
6/ Hide Licence key - i tried the censoring tool and entered my licence key, so it would display ********
But does not work here, be great to hide this key.
7/ Export members to CSV for Mailchimp
8/ Red Astericks for Required questions, verious 3rd party plugins have it for their forms within plugins.
9/ Password requiresment option, for basic passwords or option in admin to make users make a password containing caps, lowercase, and numbers.
10/ fontawesome or icon for profile signup questions, and shown on members info section on profiles
11/ recaptcha 2.0
12/ having read git hub post for the 592 post about browse members, there is no way ill be buying until that's addressed, whoever raised it, has explained the issues my friend faced, which was a headache after like 10-20 reinstalls.

**Comment by Elshara** [comment] 2017-03-14 20:22
I'll do my best to try and ease your fears.
1. Regarding profile Question Link ID system. It isn't available yet. But Social Engine has plans on doing something with it.
2. I believe Gif support is coming soon.
3. The HTML editor gets a major improvement in next version, 4.9.
4. Sign up process can be customized from the sign up section, of the admin dashboard. Social Engine may have plans to work on this feature, but for now, none as yet have been implemented in any known versions. Nice feature suggestion.
5. Profile types have no inclusion in any current working plans for social engine that I know of. This may change. Good feature suggestion.
6. Social Engine does have plans on revamping the license system. Nice suggestion.
7. A member export CSV tool does not currently exist yet in social engine. I don't know of any current plans to include one for any known version. Nice feature suggestion.
8. Good suggestion for the implementation of a * for required profile questions. This may see the light of day soon.
9. Password requirements is an interesting suggestion. Currently Social Engine does not have any working implementations for the feature.
10. An icon for profile questions would be interesting. Could you explain more about what you mean by its implementation?
11. Recaptcha will be updated soon.
12. The search for browse members issue will be fixed in the upcoming version.
Hope it helps.

**Comment by poeticjustice** [comment] 2017-03-15 02:48
1/ Be great but for now see #565 I made a tutorial how to make

2/ Gifs would be great addition

3/ I use a 3rd party plugin so can't comment

4/ would be a great feature, separating sections if I follow correctly?
Basically 1st page is email and password
Then next is the profile questions made, but you mean to break them up over pages.
So you have name DOB and gender and about me, call that personal info,
Then you want start new page for things say, social media related questions, then another page for skills or dating preferences etc blah blah?

5/different home pages and profiles, yes I have this, but it's thanks to Social engine Solutions, their plugin advance members does this

6/ dunno how to hide that, maybe custom css display: none

7/ advance members by social engine solutions shows more in it manage members page, making easier to copy all and add to csv, where as core version shows ten at a time

8/ I raised this already #548 

9/ to be compliment on ISO for internet security this may be great, but I hate the whole uppercase lowercase number add a plus sign password rubbish

10/ This would be awesome, adding a font awesome icon that is placed to the left side , prior to the text of the name of the field! Great suggestion 

11/ coming soon I think, if not SEAO have this plugin, but benefit is for more pages

12/ I was the one that discovered this! It's not good!

**Comment by Elshara** [comment] 2017-03-15 03:10
Awesome. that's 3 of us in agreement so far.

**Comment by DonnaScriptTechs** [comment] 2017-03-15 10:11
As this is not a bug, we will close it as this is for bugs and feature requests. If requesting new features, or adding bug reports, please put one item per issue raised as it makes it faster for our team to check and fix, or check and implement.

Please post at our community via your client account to ask about features after checking our blogs as we do list the upcoming features in them. Asking questions via our github slows our developers from fixing bugs as they check each github issue. 

We do appreciate feedback in the proper areas though, and will answer accordingly.

**Closed by DonnaScriptTechs** 2017-03-15 10:11 UTC

**Comment by DonnaScriptTechs** [comment] 2017-03-15 10:13
@JonSimon93 please feel free to contact our sales desk and we will personally answer your questions. https://www.socialengine.com/contact or at support@socialengine.com . You can also reach me personally at my own site forum.scripttechs.com if you can't join our client community.

**Comment by Elshara** [comment] 2017-03-15 14:51
I figured this issue was a bit off topic.

**Comment by DonnaScriptTechs** [comment] 2017-03-15 14:53
Yes but we do really want to help and really do love feedback. Our developers can get tied down with this sort of thing so we absolutely would love anyone to contact us via any of the means I mentioned. It's very important for our clients to know we do care and do love to interact with them/you. All of you.

**Comment by Elshara** [comment] 2017-03-15 16:31
Agreed. Lovely sentiment.
FYI all links to the blog on all social engine websites in control
panel just stopped working today. Tested and confirmed on the demo
site.

**Comment by DonnaScriptTechs** [comment] 2017-03-15 16:34
Regarding the blog links, thanks for posting about that. We do have a technician that's been working on it. Should be restored shortly. Sorry for the inconvenience.

**Comment by Elshara** [comment] 2017-03-15 21:54
Cool okay nice. I didn't feel like creating a whole other issue about
it. It's just something I follow gives me another reason to look at
the dashboard page every so often. Figured I'd let someone know who
was receiving notifications about a solved issue. That was you. Also
since, you post there, I wanted to let you know. Everything seems to
be back up and working now.
