### ISSUE TITLE
When Members Leave

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#204] opened 2015-07-27 01:17 UTC
When members leave, their groups and content go with them. Is there no way around this? Also, if a member with the same username as one who left decided to rejoin, they rejoin under the same user group as the left member. This could be problematic if say an admin or banned member left, if someone rejoined under that user name, they'd get admin or banned privileges regardless of their email address.

**Comment by Anshuse** [comment] 2015-08-13 13:29
Hi @Elshara , 

Regarding "When members leave, their groups and content go with them. Is there no way around this?":
One of colleague has explained very well that why we've made the system like this in issue #222 

Regarding
When you say "they rejoin under the same user group as the left member", we didn't understand your point here but all the settings, content etc of a member are bound to the member ID and not with the username. If you've faced such problem mentioned in your query above, then please let us know along with the steps and screenshots. Thanks!

**Comment by Elshara** [comment] 2015-08-13 16:57
If I signed up under a username and had been given a member level
promotion then I left the site but signed up again under the same name
and or email, the promotion would still be there even though the id
would be different.

**Comment by Anshuse** [comment] 2015-08-17 06:48
Hi @Elshara , we're not able to reproduce this issue at our end, so we're closing this.

**Closed by Anshuse** 2015-08-17 06:48 UTC
Labels: need feedback

**Comment by Elshara** [comment] 2015-08-17 07:18
Okay.
