### ISSUE TITLE
incorrect email in invitation and signup issue

### ISSUE THREAD

**Issue by dqtranmd** [SocialEngine/phpv4-issues#30] opened 2015-04-13 16:55 UTC
Invitation message shows dqtran%40gmail.com instead of dqtran@gmail.com. When user clicks on the link, this shows up in the email box: dqtran%40gmail.com. 

See invitation message below:
Hello,

You have been invited by XXXXXX to join our professional network. To join, please follow the link below:

http://connexons.org/invite/signup?code=2a3ad4b&email=dqtran%40gmail.com

----------------------------------------
You are being invited to join our professional network.
----------------------------------------

Best Regards,
Connexons Team

**Comment by Anshuse** [comment] 2015-04-16 13:24
Hi @dqtranmd ,

Thanks for reaching out!

We've forwarded this issue to our development team to have discussion over this to be resolved in future upgrades.

Best Regards,
Anshu

**Comment by Anshuse** [comment] 2015-05-19 10:38
Hi @dqtranmd ,

Our development team have looked into this and found that this is not a bug, a link is URL encoded, and thus needs to have %40

Best Regards,
Anshu

**Closed by Anshuse** 2015-05-19 10:38 UTC
