### ISSUE TITLE
Link Thumbnail Issues

### ISSUE THREAD

**Issue by leandrotavaresrocha** [SocialEngine/phpv4-issues#695] opened 2017-04-19 14:08 UTC
I already reported this type of issue before here: https://github.com/SocialEngine/phpv4-issues/issues/530

In the SE 4.9 some links still being shared without thumbnails. I already enabled iframely but no thumbnail is fetched from some page like these URLs:

https://www.catarse.me/notasvisuais
https://www.catarse.me/lebreecoelho

I already check and all these page use the facebook opengraph, so my point still. Why Social Engine cant fetch images sometimes?

Thanks,

**Comment by Elshara** [comment] 2017-04-19 14:16
Iframely isn't used in images or links yet. Just videos as far as I
know. Not even music is used by it yet.

**Comment by DonnaScriptTechs** [comment] 2017-04-19 15:32
Iframely does work for links, images and even soundcloud. 

I tested on my upgraded development site and it works. 
<img width="850" alt="ifram" src="https://cloud.githubusercontent.com/assets/6908282/25188365/d0b655ae-24f3-11e7-980e-e5f58dffaae5.png">

**Comment by DonnaScriptTechs** [comment] 2017-04-19 15:32
I'll go test on my demo site.

**Comment by DonnaScriptTechs** [comment] 2017-04-19 15:34
https://demo.socialengine.com/ it's working there too. Are you seeing any errors on your site? Did you have plugins?

**Comment by leandrotavaresrocha** [comment] 2017-04-19 15:47
@DonnaScriptTechs try using this link: https://www.catarse.me/rpgquest

**Comment by DonnaScriptTechs** [comment] 2017-04-19 15:56
@leandrotavaresrocha I tried that one on Facebook first and it does not produce an image for me there.

**Comment by DonnaScriptTechs** [comment] 2017-04-26 16:43
As we cannot reproduce this with the links that had images on Facebook too, we will close this for now. Should you be able to reproduce it in 4.9.1 once we release that, please open a new report with links that also show images at Facebook and we will test again. Thank you.

**Closed by DonnaScriptTechs** 2017-04-26 16:43 UTC
Labels: Cannot Reproduce

**Comment by Elshara** [comment] 2017-04-26 22:13
:)
