### ISSUE TITLE
Strange word division in profile textfields

### ISSUE THREAD

**Issue by adira-g** [SocialEngine/phpv4-issues#761] opened 2017-06-13 17:00 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …Edit your profile
2. …Write some words in "about me" (i.e. Lorum ipsum text with 300 words)
3. …visit the profile and check the info tab

What happens?
-------------
…Words are divided in a very strange way, it doesn't make sense (see example picture). If you check html source code with the browser, it appears, that the text is divided in exact 10-characters-long pieces and wrapped in wbr tags! (why?)

What were you expecting to happen?
----------------------------------
…Correct word dividing.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…
![screenshot 2017-06-13 18 36 32](https://user-images.githubusercontent.com/27999622/27094273-df56adf6-5069-11e7-85ff-d8838adfbf7b.jpg)

![screenshot 2017-06-13 18 59 46](https://user-images.githubusercontent.com/27999622/27094489-80af8b00-506a-11e7-8514-ed74b7c4b663.jpg)

What versions of software are you using?
----------------------------------------
**Operating System:** …nginx on Debian jessie 

**SocialEngine PHP Version:** … 4.9.2 (pure test installation, no extra modules)

**Comment by DonnaScriptTechs** [comment] 2017-06-13 17:46
I can reproduce this issue and since it is breaking some words without a - in them, it can change the meanings of the sentence depending on where the break occurs. This is especially true in some languages. 

I've added it to our issue list to fix. Thank you for the report.

**Comment by DonnaScriptTechs** [comment] 2017-07-03 18:18
We've added this to our list to fix . As this tracker is closing, we'll close this now. For new bugs, please post at our [new community](https://community.socialengine.com/forums/).

**Closed by DonnaScriptTechs** 2017-07-03 18:18 UTC
Labels: Bug
