### ISSUE TITLE
Incorrect .htaccess with Apache 2.4 causes 500 error

### ISSUE THREAD

**Issue by pjfsilva** [SocialEngine/phpv4-issues#280] opened 2015-10-14 00:50 UTC
Apache 2.4 makes a few changes on the way access control works as you can see here: https://httpd.apache.org/docs/2.4/upgrading.html "Access control".

But the file: application/.htaccess has something like this that causes error 500 using SocialEngine in Apache 2.4 and PHP 5.6:

```
deny from all
<Files ~ "index.php|css.php|mobile.php|lite.php|offline.html|maintenance.html">
    order allow,deny
    allow from all
</Files>
```

**Comment by Anshuse** [comment] 2015-10-16 13:54
Hi @pjfsilva , It would be great if you can let us know that where you're seeing 500 error on your site i.e are you seeing this error as you access your site or in any particular section of website?

Thanks!

**Comment by pjfsilva** [comment] 2015-11-03 18:47
Errors appear for example on "/application/css.php?request=application/themes/modern/theme.css&c=2" because that folder has an invalid .htaccess according to new apache 2.4

Just install socialengine with a fresh apache 2.4 installation and you will understand the problems :)

**Comment by DonnaScriptTechs** [comment] 2017-04-08 10:44
Is this still an issue for you with 4.8.13?

**Comment by Elshara** [comment] 2017-04-10 22:11
I probably suggest this to be server side.

**Comment by pjfsilva** [comment] 2017-04-24 17:27
@DonnaScriptTechs I really don't know because I don't use SE anymore. 

Please note this is a very simple problem to detect and test. Just install SE in apache 2.4. 
If .htaccess wasn't updated since I opened this the problem will still be there since the problem is that the .htaccess syntax changed from 2.2 to apache 2.4.

**Comment by DonnaScriptTechs** [comment] 2017-04-24 17:30
Ok I can't reproduce it with apache 2.4 on my installs so we'll close it for now. Thank you for your feedback.

**Closed by DonnaScriptTechs** 2017-04-24 17:30 UTC

**Comment by Elshara** [comment] 2017-04-25 07:49
.htaccess does seem to work differently in different apache versions
based on what I've noticed.
