### ISSUE TITLE
Member message not deleted via the notification area

### ISSUE THREAD

**Issue by Burno317** [SocialEngine/phpv4-issues#496] opened 2016-09-20 11:05 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)
## What are the steps to reproduce this issue?
1. Have a Member send you a message: "{item:$subject} has sent you a {item:$object:message}."
2. Go in “Yoursite.com/activity/notifications”
3. Delete that message
4. Go back in “Yoursite.com/activity/notifications”
5. The message notification is still there has been deleted.)
6. again click the link and the message is not deleted
## What happens?

When you are in:  “Yoursite.com/activity/notifications ; and you delete a message like “Yoursite.com/messages/view/id/1 “ your message is deleted but if you go back in “Yoursite.com/activity/notifications” you will see that the notification is still there and if you click that link again you will be surprise to notice that the message is still visible. In fact it will never be deleted and still visible via the notifications area Yoursite.com/activity/notifications
## What were you expecting to happen?

the notification text about that message in “Yoursite.com/activity/notifications” should disappear and removed once and for all when the related message “"{item:$subject} has sent you a {item:$object:message}." has been deleted.
## Any logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```
## Any other comments?

…
## What versions of software are you using?

**Operating System:** Windows 7

**SocialEngine PHP Version:** 4812

**Comment by Khushboo016** [comment] 2016-09-26 12:52
Hi @Burno317 , Thank you for reporting this issue, we've noted down it at our end and will fix the same in future releases of SE.

Thanks!

**Comment by Burno317** [comment] 2016-09-26 14:42
Hi,

Thank you for your fast response, I am pleased to have served the community of SocialEngine, I am just surprised as messaging is an important feature that no one has ever reported it before. My site is in test mode, I was double checking everything.

I have another bug to report that I have reported for years to the SEPHP support that that no one has ever understood and considered as of maybe today, it regards your SE chat plugin, if you go to the layout editor,  choose the “Chat Main page”  and try to add any widget (like Online Users) BELOW your content widget (chat window), then you will notice on the user side that below widget just added will always appear ABOVE the chat windows and not BELOW.

Thank you for your consideration in fixing bugs.

Have a great day.
Bruno

**Comment by Khushboo016** [comment] 2016-09-29 13:18
Hi @Burno317  , You are welcome!

And regarding "I have another bug to report that I have re":
Thanks for reporting this issue too! I am able to reproduce this at my end and we have noted down this in our internal bug tracker and will fix the same in future releases of SocialEngine.

Thanks!

**Comment by Burno317** [comment] 2016-09-29 14:29
Hi,

Thank you for your fast response, I am pleased to have served the community of SocialEngine,

I have another bug to report, it regards the full install of SEPHP 4812 that seems not be the true version 4812. 

If you make a fresh install of SEPHP 4812 and then you install the upgrade 4812 you will notice that the upgrade will install and copy about 47-48 new files, that should not to happen since you have already installed SEPHP 4812 .

If you consider that the upgrade 4812 is the true and your latest upgrade, then the full install of 4812 is indeed an old version maybe SEPHP version 4811. Please check this out.

Have a great day.

**Comment by Khushboo016** [comment] 2016-09-30 13:17
Hi @Burno317 , 

Regarding "I have another bug to report, it regards the full install of SEPHP 481":
The issue might have occurred because fresh installation of SocialEngine version 4.8.12 had not been done successfully or if you had done code level changes at your end in SocialEngine files. So, when you you would have performed the upgrade, all the changed files would have replaced with new files. I also have checked this issue at my end by performing an upgrade on my SE site on localhost that was already having version SE 4.8.12 installed and only one file was copied. So, we suggest you to recheck this issue at your end.

Thanks!

**Comment by Burno317** [comment] 2016-09-30 14:42
Hi,
Thanks for your consideration and fast response .
I have already rechecked three times this issue at my end by making 3 fresh install of SEPHP 4.8.12 on 3 different servers as I was trying to discover three different hosts, I had broken images as a test I applied the upgrade 4.8.12 and noticed everytime that 47-49 files were copied and everytime all was working fine.
I just supposed that the fresh install file SEPHP 4.8.12 was maybe version SEPHP 4.8.11 that was mistakenly renamed it can happen.
Nevertheless, I think it is a good idea to apply the upgrade from time to time just to be sure that the files core are consistent and not corrupted especially when many third pluings are installed and used.
Do you have an idea when you will release the next SEPHP version 4.8.13?
Have a great weekend.
Bruno

**Comment by Khushboo016** [comment] 2016-10-07 05:30
Hi @Burno317 ,

Regarding "I have already rechecked three times this issue":
This is not an issue of default SE version 4.8.12 and if you are still facing the same, then you can open a support ticket for this at https://www.socialengine.com/client/ticket/create or you can also send us an email at support@socialengine.com along with your site details, so we can check this issue.

Regarding "Do you have an idea when you will release the next SEPHP version 4.8.13?":
SE PHP version 4.8.13 will be launched very soon in a few days and SE version 4.9.0 is also on its way to be launched and will be released as soon as possible.

Thanks!

Thanks!

**Comment by Elshara** [comment] 2016-10-15 05:52
Related to this, installing a third party module such as comet chat removes the ability for new private messages to show up as notifications.

**Comment by Burno317** [comment] 2016-10-15 06:46
Hello,
Thank you for the information about Cometchat I suppose it is the same with arrowchat.
In my report I did not install any third party chat module like cometchat or arrowhcat.
Have a great weekend

**Comment by Elshara** [comment] 2016-10-15 07:01
Well I know the message feature is buggy at best. Could use better
integration with core for sure. Just makes it a lot worse if you do
end up installing one of the two popular html5 chats because they will
make it so that any message modules just throw an error on whatever
page they appear on breaking your website. I also think it is a
database storage issue as well.

**Comment by Burno317** [comment] 2016-10-15 07:24
Thanks for your feedback.
I have a cometchat license, when I installed it on a testing site (not the one I reported the message issue) I noticed that there are too many javascripts used so as a result the loading speed site and page are slower, so I am not using it anymore.

**Comment by Elshara** [comment] 2016-10-15 23:08
Trouble is most people use chat as a way to leave private notes for
each other rather than waiting to talk to someone if they happen to
visit the chat page. This is why comet chat is so useful. It lets you
share notes with groups of people they see when they come online,
rather than having to go look for the functionality if they are even
interested in doing so.

**Comment by shivani2910** [comment] 2017-04-11 07:28
Both issues (Member message not deleted via the notification area and Chat widget displayed in wrong places) are fixed in 4.9 when it is released.

**Closed by shivani2910** 2017-04-11 07:28 UTC

**Comment by Elshara** [comment] 2017-04-11 16:28
Awesome!
