### ISSUE TITLE
Feature request - redesign browse members as whole

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#613] opened 2017-03-20 14:52 UTC
Hi Guys over this last past month if raised a few tickets regards to profile questions and browse members.

There was one particular that i raised about browse members, after discovering that, the browse members does not communicate with the actual profile questions people put on their profile, infact a completely new database is created purely for browse members.

Which contradicts an old email/response that i had from SE ages ago.

where i questioned why can you not multi-select a single select question.
Example ethnicity. could have upto 10 entries for single select, but on browse members you can only single select search - Which is just aweful, example dating site you may like Caucasians and Indians.
But you have to conduct single searches.

SE said it couldnt be done , you couldnt have multiselect on browse if using single select box for profile questions, strang considering ive already PROVED that browse members is its own database, and its not using the profile fields database..

So why SE said it couldnt be done, PHPFOX have done it, Oxwall have done it, Phpdolphin, moosocial, buddypress, even socibd....... but not SE.

below is a image example at the bottom just after the quoted section, even in OXwall back end, aand on signup a single checkbox can only be selected on signup, but on browse member and search, you can multiselect it.

Here is what i said 

> However yes Social engine NEEDS profile questions and type of methods updating.
> Same with browse members.
>
> They seem to have never changed since when SE was first made.
> 
> Also browse members only reflects the questions.
> 
> Example say on signup, You have a single select option of
> 
> For example  Location,
> 
> On signup a members selects London
> 
> On browse members all you have is single select option, but being as your browsing the members, you should be able to multi select what your searching for on ALL questions.
> 
> So dumb you chose on sign up, but because the question was single select, it makes the browsing option single select too, which is silly
> 
> Example being, your looking for someone in London, South East (which is surrounding area), and south west.
> 
> In browse members your forced to search only one location at a time, then research the next then the next.
> This was example so don't say "but you can search miles of a location radius"
> 
> Point is the questions to browsing are horrid.
> 
> To be able to use multi select search you have to make the question on signup multi select, purely so the search can be multi selectable, which is annoying when on signup as you may only want then to select one option.
> 
> Great example of this is GENDER
> 
> You may have Male, Female and TransGender
> 
> Now on signup you will want users to ONLY select one, so its single select, you dont want a male selecting he is female too.
> 
> User on browse members , a user may like Males and Females but not Transgenders.
> 
> But the user can't search Male and Female, that user is force to search either male first, then female second, they simply can't select Male and Female......
> 
> Which is ridiculous

Here is a quote and reply from @Khushboo016 

> Hi @poeticjustice,
> 
> Regarding "This is an enhancement request that i raised ages ago, over a year ago directly":
> Thanks for your good suggestions regarding improvement of Profile questions of Multi Select Box and Multi-Checkbox type. We have added this suggestion at our end for internal team discussion, the user-interface can be enhanced by the use of Combo-boxes for such type of questions which can have multiple answers.
> 
> Regarding "To be able to use multi select search you have to make the question on signup multi selec":
> If you create a Profile Question of type "Multi Select Box" then on the Members Browse page, the search filer would also be of the type multi-select. It is not possible to have a search filter of type multi-select if you create a profile question of type "Single Select Box".
> 
> Thanks & Regards!

Not possible yet  PHPFOX have done it, Oxwall have done it, Phpdolphin, moosocial, buddypress, even socibd....... but not SE.

Maybe ask @DonnaScriptTechs since she use to work for them ;)

Browse members in 2017 should, and i really mean should have the ability to multi-check or multiselect, questions that were single select on signup.............. SE is soooo behind on this, 

Just to give the ability to multi-select search in browes members, you have to give a multi-select signup question, when really you want people to ONLY select one on signup, not ability to select more......

When you see others do it, SE cant say its not possible!!!!!

![brophpfox](https://cloud.githubusercontent.com/assets/19233272/24104752/e2a4dc58-0d7a-11e7-8342-2c82ac234228.jpg)

**Comment by poeticjustice** [comment] 2017-03-20 17:34
Be great to hear back, looking back at the 4.9 road map that was like 2 years ago and when the github posts were in the 100's issue numbers, I hope enhancements like im suggesting dont dome into play until the year 2019..... mentioned before id gladly crowdfund for SE to make enhancements quicker.

**Comment by DonnaScriptTechs** [comment] 2017-03-20 18:00
Is this a duplicate of the other request you linked? If so, I believe it was being looked at.

**Comment by poeticjustice** [comment] 2017-03-20 18:17
No not duplicate at all.

This is feature request, regards to being able to multi-select in browse members of Profile questions that were set up as single check or single select.

Something phpfox and oxwall etc have
ie
Single select on profile signup = multi-select on browse members
multi-select on signup = multi-select on browse members

But SE only mimics the question
ie
Single select on profile signup = single select on browse members
multi-select on signup = multi-select on browse members

**Comment by Elshara** [comment] 2017-03-21 16:36
This issue is a database configuration gone wrong. Discussed at length in issue 612.

**Comment by angelflo** [comment] 2017-04-24 07:03
I'm totally agree with you !! this functionnality is really important for all community website .
SE team need to update their product if they don't want to loose some customer for their competitor.
I currently need to create a commnunity website for one of my customer and I need to choose a script to start the project.
Without this functionnality, I'll need to buy phpfox solution.

**Comment by poeticjustice** [comment] 2017-04-24 11:21
Tbh @angelflo

I don't think this will ever be addressed or implemented
Social Engine have been great to fix the issues I found,
@DonnaScriptTechs @Khushboo016 have been great

But I think the profile questions files are truely so old, that they are scared to completely change them, redesign and implement better functions.

I have raised this, because it's truely needed.
I really hate how SE mimics the question in browse members.

PHPfox can do it perfectly, single select option on signup, and ability to multiselect combo boxes on browse members.

It caused me to set up such stupid questions using multiselect (purely so users can search multipul choices, when only one question is needed on signup)

Example ethnicity, only want users signing up to choose one

But in browse members I want to search a few in one hit.
If I used single select, then it's impossible for me to search, say for example 5 of 8 ethnicities, unless I set up as multi select.

But doing so, some users have selected all the choices, when they are Caucasian.

Really is annoying 
I
And also multi check and multi select are old.

I have asked many times to incorporate a tag system 
Such as selectize, which all new websites use, its cleaner and looks nicer.
Even suggested we crowd fund and as clients we pay SE to implement, but nothing :( http://selectize.github.io/selectize.js/

Was hoping with @RaymondBenc joining SE, that we would see some good that phfox has.
SE is by far superior and the custom devs are way better.

But the first point of signup is was our visitors see, so they need a whole redesign.

Placeholders, font awesome support so we can give each question a font awesome icon.
Location support with google maps api, selectize tags, ability to add questions like web links but, admin has option to set the before URL so that it's basically setting up a specific question... so we can add website question and set the prelink as http Instagram .com and then people just add the usernames 

Update to have an addition tick box on single select questions, that says "makes this multiselect search in browse members "

Also profile signup NEEDS document upload, some sites require driving licence, passports and documents. 
Having a separate section to handle document uploads is ridiculous as the drop off rate of users going to another stage to provide is 50 50.

I have so many good ideas and would gladly crowd fund to get SE to do them.

**Comment by Elshara** [comment] 2017-04-25 07:30
I'm curious.
@AlexTr @andrewboon
What's a good html5 based solution for form field type input replacing
multi-select? How would it be implemented for best use for join form
or profile questions?
Thing is, it's kind of needed to be able to show based on search
results spanning multiple profile tables. Such as if you multi-select
items, and then use such multiple selections as separate search
queries, but in one search results window. Can this be done, in your
opinion?

**Comment by RaymondBenc** [comment] 2017-04-25 08:02
I'll be looking into the technicals of this request and will factor in what version we can have this developed by. I'll circle back with an update once I've looked over the code base for this section.

**Comment by poeticjustice** [comment] 2017-04-27 00:09
Hi @RaymondBenc 

I have heard great things about you from @DonnaScriptTechs 
You sound like a legend from phpfox and now with SE.

Im hoping having insight with PHPFox, you will take the great aspects from that to SE.

Id love to hear back, I really hope its an area that can be addressed, and maybe your that man to do it.
If I had the tech knowledge to do it, Id demand a job at SE and would do it ha

This area hasn't been touched since 2012, when I first purchased with a friend.
May have been SE3 then, but i believe its not been touched since SE first released.
I apologise putting this here, but Im not using the social engine oncommunity for topics, engagement for us paid SE people and SE staff, is very low.

Now 2017

- We still have an AIM specific question..... Aim died in 2009 and was rated terribly for security, Its bad that i remember ICQ more than Aim.

- Yet instagram hasnt got a specific profile question..... which I made a tutorial on how to make #565 
Its so simple, but for people looking to buy SE now as a new client, can you imagine installing, seeing twitter facebook and AIM, and not Instagram.
You will be searching AIM to understand what the heck it is.

- single select answers for profiles, can only be searched 1 by 1. 
This is fine if you have single select between 2 answers. because if you want to see all, you dont narrow it down.
But if you have single select, with choice of 3 or more, when browsing members, its a nightmare, you have to conduct endless searches, yet PHPFOX and every other platform can do it.

- Checkboxs all fall vertically and not responsive, so if you have 20 checkboxs for a question, you have a long vertical list 1 by 1, where as all over sites sit nicely side by side and are responsive.

- Multiselect is old as, in todays generation, they are not use to this "hold cntrl and select one by one, but dont release and click as you will lose your selection"
The standard for this is http://selectize.github.io/selectize.js/
I havent seen a site for ages using multiselect about from my site running SE.

- Locations profile field needs to be linked to google maps

- http://selectize.github.io/selectize.js/ this needs to be implemented to profile signup, browse members and profiles info asap really.

- Widget for profile fields needs to be addressed.
I have over 60 signup questions, only of which 10 are visable to members on their profles.
However when a user views their own profile they see everything, but it looks nasty because they see a tool tip per hidden field, so in the end you get a long list and all that stands out is ... this is hidden repeated 50 times.............. if its hidden, dont show it at all on the widget...... visitors hate it and always question, saying its hidden but i see it.

-fontawesome icons for each question shown only on signup and profile fields widget like in #595

- This one really grinds my gears, 2017 and a required field asterisk is not shown, the single one uniform symbol everyone understands, that a field is required!!!! yet they skip loads of questions to discover they had to fill in after they hit save.............. mentally this causes people to rush and make up answers just to finish the form.... where as initially seeing it, true data inputted.
Also prevents drops offs, because they know where they went wrong.

- Placeholders, placeholders with the field box.

- multi line textbox, If question was ... what do you enjoy, you type Juggling, Swimming, Horses.....when searching in browse members, if you use it to search them terms seperatly its displayed...... but type Horses, Swimming, Juggling and you get nothing.......... hence once again why http://selectize.github.io/selectize.js/ should be built in, then each type thing will be a tag, and pulls seaches based on that tag as a combo box

- Ability to have a search from and to section.
Float does trick but only works with numbers and decimals
You need ability for single select answers to be allowed to be searched from a point to another point, basing its order how you arrange the answers.
Example height single select question
5ft
5.1ft
5.2ft
6ft
etc
thats your order so in browse members the height question shows all entries and i can select a from and end search point, just like age!

- Document uploader
Checking the identity of people is needed when signing people up, I raised a git how it should be, this is really important at signup stage, especially if you have a niche network. we are in a land of catfishes and those going by fake aliases. #710 

Ask any 3rd party dev and the one are they will never work on, is profile signup, and browse members functions to behave how i mentioned.
They will not touch it.

once again to quote SE, " It is not possible to have a search filter of type multi-select if you create a profile question of type "Single Select Box"

Yet as you know @RaymondBenc PHPFOX have done it, Oxwall have done it, Phpdolphin, moosocial, buddypress, even socibd....... but not SE

You and @DonnaScriptTechs are my only hope........ and ive stored all the above info into my R2 Unit

**Comment by angelflo** [comment] 2017-04-27 04:57
+1 to implement the @poeticjustice suggestions.
Tanks to you @poeticjustice , you have a very good analyse of the most important fetaures needed for a community website in 2017.
All your suggestion are really relevant.
Hope that @RaymondBenc  and @DonnaScriptTechs  can give a roadmap for this and can impletent these functionnalities in priority.

**Comment by JonSimon93** [comment] 2017-04-27 15:29
@poeticjustice can you go work for Social E please.

Im so annoyed Social E couldnt give me info on when a bug would be fixed that you raised, as a result I went and purchased a different script, It had best profile signup section and browse members compared to Social E.

But the script is just horrible..... then days later Social E release 4.9.1 with the fix to a bug you raised.

Yet they wouldnt tell me it was going to be fixed, just said in future......... I wanted Social E, but this was cliffhanger for me, and I repeatedly asked can I wait for 4.9 release and they honor the discount coupon,...... they ignored my emails.

SE would have had money in their bank, and I would have been happy to wait if they said "we are fixing it now, and yes we will honor the discount still"

Oh wellllllllllll i wasted money on another script that is horrible, If i can get a refund I will get SE, providing they give me a discounted rate as to when I raised countless emails.

But I agree with everything raised here, My site is planning to be aimed at adult and dating................ the profile section has never changed since SE3 and i know this as an old SE3 user.

**Comment by DonnaScriptTechs** [comment] 2017-04-27 15:53
Hi @JonSimon93 ,

We can't post when a release will come before we have the set date. At the times you asked, we were still working on the issues as you asked in 4.9.0. This fix was done for 4.9.1 which was a few weeks after the 4.9.0 release. We couldn't get it fixed in time for the 4.9.0 release but I did answer in [that other bug](https://github.com/SocialEngine/phpv4-issues/issues/592) report that we were fixing it. No emails were ignored as all were answered. However, it is possible your emails didn't reach our support if you got no answer. Please contact us again via our contact form or via support@socialengine.com and we'll address your questions. 

For this particular request, we are already looking at it per Ray.

**Comment by angelflo** [comment] 2017-04-27 16:16
Hi @JonSimon93 ,

Just for info, I wait improvement on the SE browse member to buy their script.
In the version 4.9.1 this is only bug fix, but no implementation of the features discuss in this thread.

For me, the most important feature to implement in first is the possibility to have single choice field in question (for signup and edit profile) and multiple answer choice for this question in the search form (browse member page). Without this it's impossible to creeate a community website where members can find other people by affinity, interest, etc ...

**Comment by JonSimon93** [comment] 2017-04-27 16:17
Ill message soon, Im trying to dispute a refund of another script that i purchased without thinkin it throuh properly, because I felt I wasnt getting an answer.

I should have ben more paitient like @Elshara and @poeticjustice said, but i assumed it be a year away.

I only came back to gitub as Poetic referenced my idea in a post that was closed recently for him #709 
and my orignal post was #595 but i heard no more about it.

I always love ideas from @Elshara and @poeticjustice , them two seemed so clued up, Id imagine they have good niche communities.

**Comment by JonSimon93** [comment] 2017-04-27 16:22
@angelflo Im refering to this bug which @poeticjustice did a big inspection into.

It was a bug i experienced years ago with a friend, and it killed our site, we couldnt work it out, then Poetic layed it out with diagrams and then it was fixed.
https://github.com/SocialEngine/phpv4-issues/issues/592
 but the fix came week after release of 4.9 with 4.9.1 
And I wanted to buy SE when they did the 4.9 pre release offer

**Comment by poeticjustice** [comment] 2017-04-27 16:28
@angelflo I'm so glad someone else see's this, I've been banging on about profile signup and browse members for ages, Do you agree it's literally the most important thing.

I was forced to make the most ugliest signup form once, I have ethnicity as a question, but had to set as multi select, just so it could be searched in browse members......... but only wanted people to choose one answer, as a result people chose multiple items just to be seen more in all searches.... was annoying

**Comment by DonnaScriptTechs** [comment] 2017-04-27 16:29
Hi @JonSimon93 , sounds good regarding emailing us soon. If you still don't get an answer, please get in touch with me at my https://forum.scripttechs.com ,  https://forum.scripttechs.com/messages/add/data66 right there, so that I can make sure you're taken care of. I'm curious as to which script it was too (the one Ray and I used to work for or something else). Some will refund but that one doesn't. 

Regarding this improvement though, we'll see what can be done. We need to try to keep this issue on track so that when Ray comes back to it, he doesn't have to look through a lot of comments.

**Comment by gsf00001** [comment] 2017-04-27 16:33
(Donna: after I began my comment yours posted with suggestion to keep this on track w/o lots of comments - I believe the below is on track).  

My suggestion is to be sure this is flexible and doesn't lock others into a different mold on this multi-select.

Multi-Select (conceptually) can be used in an 'and' or 'or' situation, depending on the needs of the ADMIN.  This is why I had some Search widgets customized to meet all or any criteria.  This allows the actual User to decide how narrow or broad their search is.  My concern was the possibility of keeping things 'on track' for this issue may gain required functionality for some, but remove functionality for others.

**Comment by JonSimon93** [comment] 2017-04-27 16:36
@DonnaScriptTechs I went halfs with my friend on phpfox.

It looked nicer, I loved the default images with initials, and its browsing of members was better single select answer, and seemed to do multi search, but it was awful to use, i really didnt like it.

wen buying they say "License comes with a Free 14 day full version trial" yet this means nothing when you buy it as they wont refund

**Comment by DonnaScriptTechs** [comment] 2017-04-27 16:42
@gsf00001 the above link to that js search showed a "tag" sort of search.  http://selectize.github.io/selectize.js/ which should work for any needs (narrow or broad search). However, js doesn't play nicely with moo so we need to look at options or make our own. Does that look like something that would work for your needs, that sort of a search feature?

@JonSimon93 hopefully it'll work out for you to get a refund. I know that script very well.

**Comment by poeticjustice** [comment] 2017-04-27 16:51
@gsf00001 multiselect can stay as it is, SE can can leave it alone for all i care, its nasty and old, What i have suggested is basically more default specific profile questions,

Tags being one of them, similar to multiselect but tags.
tags that appear inline of the search field they are selected, which can be deleted by reclicking them.
or it places the tags next to the search button of browse members with also a clear all tags button.

Having single select question should have an option in the back end when setting up the question
A Tick box that says "make this single select question a multiple select within browse members?"

The new thing for multi select type search is Tags and Also this new one I've seen, best way to explain is on off switch buttons.

Its literally just making new specific profile questions.

For a single select question, it could simply offer my settings in its set up like 

Single select
- name
- description
- placeholder (requested feature)
- font awesome icon (requested feature)
- make searchable on a multi level on browse members, if unticked this search will be only single select search (requested feature)
- make searchable as a from to end point search - ticking this will disable being a single select search or being a multi search only on browse members, the order of answers determines the from and end point search values - eg Height (requested feature)

**Comment by DonnaScriptTechs** [comment] 2017-04-27 17:00
@poeticjustice typo. I mean jq (jquery)

**Comment by gsf00001** [comment] 2017-04-27 17:01
@poeticjustice Great!  Yes, the last 2 items you included are what I wanted to be sure SE realizes and would implement - provides lots of flexibility (not quite as much as I'd like, since some things should still be up to the User at the point of search), but it at least alleviates my fears :)  Thansk for the helpful extra details.

**Comment by poeticjustice** [comment] 2017-04-27 17:05
Awesome @gsf00001 ............. so when is SE hiring me as a think tank lol 
Oh yes JQ, the selectorize was just an example that i found to best describe it all, May be able to be done using other methods maybe, we shall see for the legend @RaymondBenc 

Been a good productive afternoon

**Comment by Elshara** [comment] 2017-04-29 14:00
The way I see it, we have 3 options.
1. Member search belonging to content they share inside as well as
outside of their profile.
2. Tags, specifically designed for member search feature.
3. Profile questions, designed for integration of both search and
category based mapping.
We need to simplify profile questions regardless, to ensure 5 types of
question requirement exist.
1. Text input. Decide whether it is single, or multiple line, but only
one should be there.
2. Multiple selection. It doesn't matter if you have only one answer
for people to choose from, as long as you can add or remove the
ability to select how ever many items out of what ever is actually
possible through its implementation can be done based on requirements.
3. Dependency. Integration with profile dependency allows different
sub questions to be associated with it. Categories, requirements,
custom fields and default selections are possible here based on
initial input.
4. HTML embeds. Profiles need the ability to have custom script
implementation, so you are able to place content there of your own
choosing. The content you place may be anything from personal like
buttons of social media pages, to custom information and scripts or
counters. The important thing is, the ability exists.
5. Custom CSS. Styles are important, and should probably be contained
within an html section, however it would be nice to provide such
ability for people to highlight important answers.
All field types must be interdependent, yet have the ability to edit
10 things associated with them for integration purposes.
1. Member privacy. Giving users the ability to keep information
private, or public, based on who views their profile.
2. Name and description of the question. Allow site admins to
optionally have such.
3. Member tags for each answer. This way members can tag their
answers, to appear in search results, if their answer is a search
string, they can lead people to their profile using them in addition
to default answers.
4. Custom error messages. For dependency based fields, it would be
ideal to set up custom error messages if the question isn't answered
according to the correct sequence.
5. Custom style. To optionally highlight members answers, or to show
or hide others by default.
6. Profile groups. To allow certain questions to be contained within a
group. Each group would contain its own heading automatically.
7. Categories. Allowing people to be based in different categories or
member levels based on dependency sequences.
8. Matching. Allow members to be matched based on their association to
search results for other members to see suggestions about the match,
and to view it, for relationship purposes.
9. Requirement check. Provide the option to require certain types of
input, to be shown if multiple selections contains conditions.
10. Approval integration. For dependency fields or groups to have
approval regulations contained within answers which aren't ideal for
the sequence of conditions specified through multiple selectors or
default configuration.
Member browse would simply work by allowing each answer to be
contained within its own connected database to the field itself. The
database field would contain one answer per section, so each cell
belonging to a field group, could contain independent status.
It's time to start providing iframely integration for embeds if
possible. Profile questions containing external content, could use
such an ability with great accuracy.

**Comment by DonnaScriptTechs** [comment] 2017-05-16 10:47
This issue was moved to SocialEngine/phpv4-feature-requests#56

**Comment by DonnaScriptTechs** [comment] 2017-05-16 10:48
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.

**Closed by DonnaScriptTechs** 2017-05-16 10:47 UTC
