### ISSUE TITLE
Fix Location Of Site Name

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#200] opened 2015-07-26 23:55 UTC
Currently we do not have the ability to choose whether the site name appears before or after the page title. Nor do we have the option of choosing where the page title appears across the bar. I'd like to either introduce an icon there or a logo of some sort, and also be able to move the site name to the end of the page title so instead of the site title being mysite.com - members browse it would be browse members - mysite.com or something like it.

**Comment by smazurov** [comment] 2015-07-27 00:16
duplicate of #148

**Closed by smazurov** 2015-07-27 00:16 UTC

**Comment by Elshara** [comment] 2015-07-27 02:14
OH  okay.
