### ISSUE TITLE
Problem Accessing Server Extensions

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#666] opened 2017-04-14 04:45 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Install a package from package manager.
2. … Once at the dependency check, look for items it isn't able to check. Such as Mod Rewrite.
3. … Install it anyways.

What happens?
-------------
… The system is unable to detect accurate server settings at all. It isn't able to connect to directories apart from public_html either. It can't connect to ffmpeg, mod rewrite or other php extensions located on the server. It just blindly assumes they are activated unless a module requests it, then it just assumes it isn't there, even if it is. For example, the only reason why mod rewrite would work, is due to the .htaccess hack.

What were you expecting to happen?
----------------------------------
… Social engine to be able to check to see if php extensions outside the base folder are activated as the script is supposed to do. Such as ffmpeg and mod rewrite among others.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Better integration of server specs would be a great start.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by SpiritWolfie** [comment] 2017-04-14 09:52
Can confirm this one, mod rewrite never detects for us, yet every other engine we have installed detects mod re-write just fine, Same with the gif extension thing, other detect, but SE does not

when -everything- else detects it perfectly and only one thing does not, it has to be a issue with the product.

**Comment by DonnaScriptTechs** [comment] 2017-04-14 13:48
I just updated my live demo and wasn't able to get the error you show when I was adding the packages but I don't have any third party products to test other than my own small widgets and the core plugins which didn't cause this issue. Not saying it doesn't happen though. Just that I can't get it to happen on cazaratech's VPS where my demo is or on his cloud where my author site is.

**Comment by Elshara** [comment] 2017-04-14 15:47
I see.
So not every server is configured the same. Does ffmpeg or mod rewrite
show up for you if you go to the server stats area and click on server
information? You'd think or assume, it would show up there, seeming as
how it's a server extension.
Because it doesn't show up on ours even though it's enabled. I'm
talking core plugins here by the way. Not third party. Just package
manager in general. Even prior to the installation of any plugins, the
default package when you upgrade say version x to version y for
instance of social engine core. That's where this would show up under
requirements check. As well as if you go to packages and plugins
dependencies area.

**Comment by DonnaScriptTechs** [comment] 2017-04-14 15:57
Yes, mod_rewrite shows in the list. I don't have video upload on my server so that won't show up.

**Comment by DonnaScriptTechs** [comment] 2017-04-14 15:58
I had no errors showing in package manager when upgrading for anything missing. I'll go look around more.

**Comment by DonnaScriptTechs** [comment] 2017-04-14 16:02
Plugin dependency screen is green except for Imagick as this demo needs to move to an SE server (it's on a fox server) so I don't have that on this one. GD shows fine. I also don't have APC on this one. I'll check it again today after it moves to an SE optimized server at cazaratech.

**Comment by Elshara** [comment] 2017-04-14 17:03
Okay. My point is proven. I have that module, but not mod rewrite or ffmpeg.
Interesting. Because you'd think it would show up in the list. The
fact it does for some people, but doesn't for others, and yet it
exists for them, is a bit concerning.

**Comment by DonnaScriptTechs** [comment] 2017-04-14 17:11
It would require more checking. Such as, are there any firewalls blocking things ( I had this as mod_sec was enabled ) or other checks to see what could cause the issues since more than one of you is experiencing the issue. That's why I am not marking this as I'm not a server expert as you can see. I want one of our technicians to see this and check for issues.

**Comment by Elshara** [comment] 2017-04-14 17:31
Agreed. I know Mod Sec is enabled on the server where I'm at and I
don't have root access to it.

**Comment by DonnaScriptTechs** [comment] 2017-04-14 17:33
http://support.socialengine.com/php/customer/portal/articles/1649350-socialengine-requirements yeah it's recommended to disable it.

**Comment by gsf00001** [comment] 2017-04-14 17:35
@SpiritWolfie "when -everything- else detects it perfectly and only one thing does not, it has to be a issue with the product."

Not necessarily.  That's like saying because I get along with everyone else except you that it must be your fault :)   

When I initially had SE installed on a dedicated server at 1and1, no one I contacted could resolve the modrewrite issues I had with SE (not 1and1, SE, SEAO, and other 3rd-Party Devs I contacted).  The Server (and other scripts that used modrewrite) were fine - just not SE.  But after I switched to FastComet (initially a dedicated server, now a VPS) everything is great.  

Not saying it isn't an issue with SE and something else - just that the 'something else' could be more the culprit in this case.  But I could be wrong - won't be the first time... today.

**Comment by Elshara** [comment] 2017-04-14 21:00
that's kind of what I was trying to say in different wording, two.

**Comment by poeticjustice** [comment] 2017-04-15 23:13
Fastcomet are the best, they actually know what they are doing with the linode servers they use, I have Cloud VPS

All other hosts are rubbish, esp hostgator, I had a Dedicated server and they purposely crashed my server and deleted everything and just refunded me, saying dont support SE..... after 4 months of working..... all i asked was for them to change one setting lol

**Comment by Elshara** [comment] 2017-04-16 05:44
Wow. I'd sue them.

**Comment by Elshara** [comment] 2017-04-16 05:46
Only way I will be using fast comet is if I get full root access.
Their default packages just suck. I hate how expensive they are just
for a gig of ram and like not even 50 gigs of hard drive space for
full root access. That's not including cpanel plus whm on a custom
license and cloud linux to test various php environments.

**Comment by gsf00001** [comment] 2017-04-16 16:02
@Elshara Not sure what you mean by no full root access - my dedicated and VPS plans had it.

As far as 'expensive', that's a relative term.  When a Host (like FC) can resolve an issue in a matter of an hour or so that others (SE, SEAO, 1and1, other 3rd-Party Devs) couldn't resolve in multiple tickets over the period of a month or so - what's that worth?  You're paying FC for highly knowledgeable expert support, not just for hardware (and there's is fast hardware including SSDs on most plans).  To have a host like FC that provides me peace of mind is worth much more than what the monetary costs are.  My initial page load times went from over 30 seconds (at 1and1 on a $400+/month server - with only 1 User... me) down to typically <7seconds (and that's with about 150 Plugins).  

I'm no SE expert so I am willing (and happy) to pay for expertise.  If I knew more, I'd probably still be willing (and happy) to pay FC because 'knowing more' still doesn't make me an expert with SE and hosting and linux and servers and ... etc.   The peace of mind knowing that I can say 'hey - I have a problem and need some help' and have it resolved very quickly instead of days/weeks of finger-pointing, is worth a lot to me.

**Comment by poeticjustice** [comment] 2017-04-16 16:50
FastComet are totally worth the price. I pay £75 a month.

Issues sorted within a hour max, havent waited longer than that, and knowledgeable of SE, Plus they gave me my own SSL cert forever for free.

TMD Hosting..... cant even address simple tasks, my friends SE site went down once.... took a week to get it back up and running.

Hostgator.... and i have this in writing. If you buy hosting where you use upto 80% discount, they wont help you.
I had so many issues, and site was working for 4 months (setting site up)
I asked them to change a setting in WHM, they did, and it killed the server, they kept trying to reset server and it had died, lost everything.
They tried blaming SE script, then tried saying i had 100 concurrent users, they kept lieing.
I esculated and caught them out, and I woke up to a full refund for a dedicated server, and the email said, It wasnt worth their time to fix the server and give service or advice regards to a SE hosted site, because I paid $200 for a $1500 dedicated server for 2 years lol

So yes paying more for FastComet is the only way forward for me!

**Comment by Elshara** [comment] 2017-04-16 19:01
I like their pricing plans though. 80% off and it's supposedly your
own dedicated server! They can't f*** you over like a hosting company
can on shared hosting. Even then you have limits, rules etc as a host.
I'm tempted just to get one for the price.
Fast Comet tried charging me $69.00 a year for their lowest price SSL.
I don't know if their policies have recently changed but free ssl
generally means free doesn't it?
Actually it was with host iso I got the free ssl domain and everything
else which came with it.
$75.00 a month sounds way cool! Did you get the full dedicated server?
They tried charging me $200.00 a month, over $200.00 more like $230.00
or $240.00 plus taxes American. Canadian I was looking at a $310.00
bill and that was a bit expensive for me. Tell me where you can get a
good, cheap, dedicated server and I'm drawn like a moth to a flame.
Otherwise, I'm okay with shared hosting. Almost everything I use is
based on packages and plugins which derive from it.
I can pay $200.00 Canadian a year and get a decent, if a bit limited
hosting plan. Value 4 G with name cheap plus dedicated IP and I pay
extra for the domain, SSL and everything else is included. Free
support two. Prices may have dropped since I bought it over two years
ago.

**Comment by DonnaScriptTechs** [comment] 2017-04-26 16:53
As we cannot reproduce this, we will close it. However, if you have issues still after trying 4.9.1 we would need to check on your server if you have support access. Things like this are hard to track down unless we can see the issue. It could be the servers are configured differently than we expected.

**Closed by DonnaScriptTechs** 2017-04-26 16:53 UTC
Labels: Cannot Reproduce

**Comment by Elshara** [comment] 2017-04-26 22:09
Thanks for the tip.
