### ISSUE TITLE
Problem with posting youtube videos from activity feed

### ISSUE THREAD

**Issue by maxx24** [SocialEngine/phpv4-issues#44] opened 2015-05-19 00:59 UTC
I wanted to report a bug that has appeared in the past week......when you try add a video thru the activity feed, the title and description of the video is no being trasferred from youtube. Instead,
the title and description become the following: "https://youtube.com/devicesupport"

**Comment by maxx24** [comment] 2015-05-19 01:01
Just found this.......https://support.google.com/youtube/answer/6098135?p=yt_devicesupport&hl=en&rd=1

Will SE address this issue?

**Comment by Anshuse** [comment] 2015-05-19 12:54
Hi @maxx24 ,

Thanks for reaching out.

We've forwarded this issue to our development team to have discussion over this to resolve this in near future upgrade.

Best Regards,
Anshu

**Comment by jkwas** [comment] 2015-05-20 22:06
Writing here to say that I'm having the same issue too.

**Comment by swishemart** [comment] 2015-05-20 22:08
Confirmed on our install also - looking forward to a fix.

**Comment by MiamiShade** [comment] 2015-05-21 00:33
Perhaps a good reason why an option to disable youtube or vimeo would help.

**Comment by Anshuse** [comment] 2015-05-25 13:16
Hello @maxx24 , @jkwas , @swishemart ,

We've discussed this issue with development team and we're going to resolve this issue in next version i.e 4.8.9

Best Regards,
Anshu

**Comment by Anshuse** [comment] 2015-05-25 13:17
Hello @MiamiShade ,

We've reported your suggestion in our internal suggestion tracker for our team to have discussion over this.

Best Regards,
Anshu

**Comment by darkasylumradio** [comment] 2015-05-27 21:47
thanks look forward to it

**Comment by swishemart** [comment] 2015-05-30 19:49
Is there any fix for this before 4.8.9 comes out or is it coming out soon?

**Comment by Voxitt** [comment] 2015-05-31 22:21
Is there any fix before 4.8.9 is released. We are launching our site in the next few days  and need this functionality to be working.

**Comment by smazurov** [comment] 2015-06-01 17:38
We're working on it in 4.8.9, but given the scope of the issue it unfortunately cannot be a quick fix. 4.8.9 should be out soon (we're actively working on this and other priority fixes now).

**Comment by Domokun** [comment] 2015-06-04 07:26
Hello!

Thanks for the answer! I have read in another thread, the 4.8.9 that this update will be released in 2-3 months, adding the responsive theme. It was 28 days ago approx.

My site relies heavily on youtube videos, and we have our own custom responsive theme. What I mean is... is it possible to have a quick fix for that instead of having to wait for a whole new release, whose new features we will not probably use as our site was fully customised and is working perfectly?

Please, don't take it as criticism, it is a practical question. No youtube videos, then we're dead.

Kind regards!

**Comment by smazurov** [comment] 2015-06-04 07:46
Responsive theme is planned for 4.9.0, which is indeed further away. 4.8.9 is much closer to being released. We know this is a big deal to a lot of people and are working on having a fix out asap

**Comment by pacodrums** [comment] 2015-06-05 01:43
This failure is serious, please do not take time to fix.
The videos are now a potential traffic generator

**Comment by smazurov** [comment] 2015-06-05 01:44
> We know this is a big deal to a lot of people and are working on having a fix out asap

**Comment by coder4web** [comment] 2015-06-06 07:57
Another confirmation of this problem. This is about YouTube API migration to v3 (v2 which SE 4.8.8 use is deprecated now). Need ASAP fix.

**Comment by darkasylumradio** [comment] 2015-06-06 19:01
yep i got bad feeling now as i not able to add any new videos now , so looks like the turned off the old API , so we have no access to any new videos

**Comment by Domokun** [comment] 2015-06-06 21:11
Hello all,

in our case (we are under 4.8.6) the videos already embedded are still available, so it's something.

By the way, this issue should have been foreseen, as Youtube wouldn't change its api without warning in advance, i guess....

**Comment by kain2142** [comment] 2015-06-08 14:55
This was announced in March 2014:
http://youtube-eng.blogspot.de/2014/03/committing-to-youtube-data-api-v3_4.html
"To focus on improving v3, it’s time to say goodbye to our old friend, v2. In keeping with deprecation policy, most API functionality will remain available for use until April 20, 2015, so you have more than a year to move to the new API"

In your blog post about PayPal API changes you wrote:
"We take such compatibility issues very seriously and dedicated our technical team to get this fix out right away after receiving PayPal’s notification."
http://blog.socialengine.com/2014/11/25/important-compatibility-fix-for-websites-using-paypal/
So why not on this compatibility issue?

We are very unhappy.
![sad-sad-face](https://cloud.githubusercontent.com/assets/5647094/8037628/2890d654-0dff-11e5-983f-6029b8f122ae.png)

**Comment by myetter37** [comment] 2015-06-08 18:30
Hi everyone,

As you are aware, YouTube integration with the current version of SE PHP is defunct due to YouTube depreciating their API v2. We understand that many of your sites depend on YouTube video integration in order to function properly, and this issue has caused you much anguish. We should have been preemptive in handling this issue before it became a problem, but other pressing matters seem to always be demanding the attention of the dev team. We apologize deeply for not making this update a priority sooner.

The good news is our dev team has implemented a temporary fix that you can apply until we are able to release version 4.8.9 (which is almost ready). Please follow these steps to resolve the issue:

[Click here](https://s3.amazonaws.com/se4-downloads/misc/youtube-fix.zip) to download the `application.zip` file
Extract the file to get a folder named `application`
Upload that `application` folder on your server via FTP, which will merge it with the existing `application` folder
Or, alternative to uploading the whole folder, you can manually upload each file in the downloaded `application` folder to the `application` folder on your server (be sure to put them in the corresponding directory path)

Again, this issue will be resolved in the upcoming 4.8.9 release. If you have any further technical questions about this process, please contact our support team who will be happy to help out. Thank you for your patience and understanding.

**Comment by darkasylumradio** [comment] 2015-06-08 22:36
yep fix does not work at this end as well

**Comment by meetgerry** [comment] 2015-06-08 23:41
![2015-06-417](https://cloud.githubusercontent.com/assets/8540750/8047660/f461bab8-0e50-11e5-891c-b12c79686137.png)

**Comment by meetgerry** [comment] 2015-06-08 23:41
![2015-06-417](https://cloud.githubusercontent.com/assets/8540750/8047666/0b391b6e-0e51-11e5-813f-f6dab781cb4f.png)

**Comment by smazurov** [comment] 2015-06-08 23:42
anything in the error log?

**Comment by Domokun** [comment] 2015-06-08 23:45
Hi!

First of all, thank you for the fix! In our case, it has disabled the possibility of adding youtube videos, offering only the possibility of adding Vimeo.

Anyway, as we are using third party plugins, we guess that we have to wait first for the 4.8.9 and then wait until this 3rd party release their own fix for the plugin.

:(

**Comment by smazurov** [comment] 2015-06-08 23:50
Ah, one thing I forgot to mention mention is that new Google API requires you to sign up and generate an api key. There is a new setting in the admin to add a google api key, if you don't have it entered in, youtube option is not visible anymore. 

@Domokun please sign up for a google api account, enter the key, and try again.

@meetgerry did you enter a key in the admin settings, is it valid?

**Comment by darkasylumradio** [comment] 2015-06-08 23:57
were about is the google api? on the admin account then look but cant see it?

**Comment by smazurov** [comment] 2015-06-09 00:15
its under Plugins -> video -> global settings.

**Comment by Domokun** [comment] 2015-06-09 00:25
Hi,

I am sorry but I still can't, even with the API....

**Comment by darkasylumradio** [comment] 2015-06-09 01:04
so make youtube v3 API Client secret: ????? after i did this still the same

**Comment by smazurov** [comment] 2015-06-09 01:06
we'll certainly look into it but you guys are not providing us with a lot of info. If you could, use our [bug submitting guidelines](https://github.com/SocialEngine/phpv4-issues/blob/master/CONTRIBUTING.md#bug-reports) to provide more info.

**Comment by darkasylumradio** [comment] 2015-06-09 01:16
sure happy to but its like 2.20 am here in the uk , it have wait until i get up. my head will be in better place. but can't seem get working., (maybe you can give use some more info on how make API key maybe were doing it wrong?. (

**Comment by pacodrums** [comment] 2015-06-09 01:18
I iuse the api public, and activate for youtube appi V3. But i have this error. 

Fatal error: Can't use method return value in write context in /home/batac05/public_html/application/modules/Video/views/scripts/_composeVideo.tpl on line 44

Any ideas?

**Comment by shivani2910** [comment] 2015-06-09 05:11
Hi everyone,

If the above provided fix is not working on your installation and you're unable to file a support ticket, then please send to us a message via contact form ( http://www.socialengine.com/contact ), or you can also send an email directly to support@socialengine.com providing details of the issue and below details of your website so that we can check everything at your end and get back to you soon:

Admin Login Details:
URL:
Email: 
Password

FTP details:
Host:
Username:
Password:

Thanks

**Comment by smazurov** [comment] 2015-06-09 06:07
to add on to the thread, please make sure you enable youtube data in the api where you get your key. We're obviously going to make that process a lot easier and describe it over the next week.

**Comment by kain2142** [comment] 2015-06-09 08:53
Hi,

thank you for the fix, it works pretty well.
A big enhancement would be to reduce the two API-requests in "checkYouTube" and "handleInformation" to only one request, since there are some daily limits on the API. 
I'm looking forward to see that in the 4.8.9 release.

Thanks and Greetings.

**Comment by shivani2910** [comment] 2015-06-09 10:04
Hi @kain2142,

Thanks for your feedback.
Regarding daily limits on the YouTube API, We use this API during video creation on website to fetch details of a particular video from YouTube while the daily limits for such read operations is too huge that will not get exhausted. You may also check this URL for more details: https://developers.google.com/youtube/v3/getting-started#quota

Thanks

**Comment by Domokun** [comment] 2015-06-09 11:05
this is what we get :(


2015-06-09T10:57:50+00:00 CRIT (2): 
Error Code: 292983
exception 'Exception' with message 'DateInterval::__construct() [dateinterval.--construct]: Unknown or bad format ()' in /home/mysite/public_html/application/libraries/Engine/Date.php:48
Stack trace:
#0 /home/mysite/public_html/application/libraries/Engine/Date.php(48): DateInterval->__construct('')
#1 /home/mysite/public_html/application/modules/Video/controllers/IndexController.php(1010): Engine_Date::convertISO8601IntoSeconds(NULL)
#2 /home/mysite/public_html/application/modules/Video/controllers/IndexController.php(257): Video_IndexController->handleInformation(1, 'KWZGAExj-es')
#3 /home/mysite/public_html/application/libraries/Zend/Controller/Action.php(516): Video_IndexController->createAction()
#4 /home/mysite/public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('createAction')
#5 /home/mysite/public_html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#6 /home/mysite/public_html/application/modules/Core/Bootstrap.php(75): Zend_Controller_Front->dispatch()
#7 /home/mysite/public_html/application/libraries/Engine/Application.php(160): Core_Bootstrap->run()
#8 /home/mysite/public_html/application/index.php(205): Engine_Application->run()
#9 /home/mysite/public_html/index.php(24): include('/home/mysite/...')

**Comment by Domokun** [comment] 2015-06-09 11:08
well now when we want to send a message to a contact, we get:

Fatal error: Can't use method return value in write context in /home/mysite/public_html/application/modules/Video/views/scripts/_composeVideo.tpl on line 44

**Comment by shivani2910** [comment] 2015-06-09 12:47
Hi @Domokun,

Thanks for the message. Best way to enable us look deeper into this problem on your website would would be to send us a message via contact form ( http://www.socialengine.com/contact ), or you can also send an email directly to support@socialengine.com providing details of the issue and details(Admin login and FTP) of your website so that we can check everything at your end and get back to you ASAP. 

Thanks

**Comment by Elshara** [comment] 2015-06-10 04:50
You guys. Do the following.
1. Start a new project, an api project in Google developer console.
2. Click on API Auth after accepting the terms of service, you'll be presented with a check box and a confirm button, in a pop up box, click the check box first then the confirm button.
3. Click on list of apis.
4. Click on youtube data.
5. Click enable.
6. Go back to the list of apis.
7. Click on youtube analytics.
8. Click enable.
9. Go to credentials under api auth.
10. Click Create new Client ID.
11. Fill in the information for your website then hit save.
12. Go back to credentials.
13. Click on create new  key.
14. Don't choose server, choose browser.
15. Make sure all referrals is checked by leaving the field blank if you want others to use the app, otherwise type in the name of your domain then click save.
16. Go back to credentials.
17. Copy the api key, right click the paragraph where it is found and click select all, then right click it again, click on copy.
18. Go to your video global settings page in social engine and paste the key in there, then hit save.
19. You're done, try posting a new youtube video.
20. Update this info if I missed something, terminology or otherwise I posted this at the top of my head.

**Comment by darkasylumradio** [comment] 2015-06-10 12:54
Elshara thanks now working great

**Comment by dvital** [comment] 2015-06-10 16:50
HI,
Thanks for the fix. I'm using SE 4.8.8 video plugin 4.8.7 and the fix works fine.
Dan

**Comment by myetter37** [comment] 2015-06-10 16:56
Hi all,

We apologize for the continuing problems with this issue. Thank you for being patient and for your feedback as we figure out a better solution.

I just got word from the dev team that the application folder that I linked above did not work with some specific server configurations. The team has updated the file and they've confirmed that it's working now.

Please [click here](https://s3.amazonaws.com/se4-downloads/misc/youtube-fix.zip) for the new file, and continue to let us know if you see issues. Again, this fix will be included in SE PHP 4.8.9. Thanks!

**Comment by Domokun** [comment] 2015-06-16 21:07
Hello,

first of all, thank you for the support. We are using a third party plugin (Social Engine Addons) being the main component of our site their Pages plugin with the videos extension. They can't fix it until the 4.8.9 is released.

When will be released the next update? the whole experience is being very frustrating, as we made the presentation last week without being able to use the most important feature of our site, having paid this month's community managers salaries among other things, that have to be paid the next month too and so on. We may say that the official launch of our site, is being a disaster.

Thank you in advance for your answer.

**Comment by MMAMELEE** [comment] 2015-06-17 03:38
Does the option to add the API key in the global setting on the video tab only show up after you installed your new "Application" file? Because I don't see it there currently before hand.  Also If you just upload the application file will it merge like you said or will it replace the existing one with the new one that doesn't have all the files?

**Comment by MMAMELEE** [comment] 2015-06-17 16:28
what should the file permissions be set at?

**Comment by MMAMELEE** [comment] 2015-06-17 16:45
the fix worked

**Comment by shivani2910** [comment] 2015-06-18 09:58
Hi @Domokun,

We understand what you're trying to say. We're very close to releasing the next version of SocialEngine PHP that will be including this fix. There are just a few more important things that we wanted to incorporate in this release. Please be assured that it'll be live in the coming week.

Thanks for your support and patience.

**Comment by shivani2910** [comment] 2015-06-18 09:59
Hi @MMAMELEE,

We're glad to know that it worked for you. Please let us know if you've any further queries.

Thanks

**Comment by ClubbinHeaven247** [comment] 2015-06-21 21:01
Hi this fix worked for me although the only annoying thing is that the youtube videos do not enlarge full screen althought they do when you add a vimeo video.
So i take it this is still down to a api issue command?
Help please :)

**Comment by myetter37** [comment] 2015-06-22 22:50
SocialEngine PHP version 4.8.9 has been released, and this issue has been fixed in that release.

**Closed by myetter37** 2015-06-22 22:50 UTC

**Comment by orikook** [comment] 2015-06-23 05:18
Thanks for the fix! 
Can you tell whether the fix in 4.8.9 is exactly the same as the fix that you've published earlier in https://s3.amazonaws.com/se4-downloads/misc/youtube-fix.zip or maybe you've made changes in the fix since then?
I am asking this because I can't upgrade to 4.8.9 but I want to keep my youtube fix up to date.
Thanks again!

**Comment by smazurov** [comment] 2015-06-23 05:19
Yes its essentially the same, you won't miss any functionality.

**Comment by Domokun** [comment] 2015-06-25 12:23
great, thank you !!

**Comment by MMAMELEE** [comment] 2016-12-27 07:34
Guys I updated to the current version 4.8.13 and my thumbnails are gone again on my video whats could be going on?

**Comment by Khushboo016** [comment] 2016-12-27 07:55
Hi @MMAMELEE , Please clean your browser cache and then reload your site to check if this issue exists or disappears. If the issue still persists, then flush server cache from "Admin" > "Settings" > "Performance & Caching" section of your site and recheck the issue. And if the issue still persists, then please send us an email at support@socialengine.com, so we can check the issue at our end.

Thanks & Regards!

**Comment by MMAMELEE** [comment] 2016-12-27 08:18
@Khushboo016 hey but I flushed the caching in the admin panel and the cache on my browser and its still giving me the We could not find a video there - please check the URL and try again. If you are sure that the URL is valid, please click here to continue. error and not uploading thumbnails and today i updated to the latest versions of every SE php. Please help further assist if you can please..thanks happy holidays
