### ISSUE TITLE
Videos cannot be added to blog posts

### ISSUE THREAD

**Issue by maxx24** [SocialEngine/phpv4-issues#250] opened 2015-08-15 04:13 UTC
The feature to add a video to a blog post via the URL/embed button is not working. Has not worked for some time. Is this documented?

**Comment by Anshuse** [comment] 2015-08-17 10:16
Hi @maxx24 , To embed the video from "embed" tab in the Blogs module, you must be copying the embed code with an "iframe tag" so, please make sure that you've added "iframe" tag in the "allowed HTML tags" field for each Member Level under "Member Level Settings" tab in Blogs module.

For example, embed code look like <iframe width="560" height="315" src="https://www.youtube.com/embed/P-gUEzsesjU" frameborder="0" allowfullscreen></iframe>

If you've already added iframe tag for each Member Level and are using correct embed code of video but still facing same issue then issue seems to be existing in your specific installation and for that you may open a support detail along with your site details. Now here, we're not able to reproduce this issue at our end so, we're closing this ticket.

**Closed by Anshuse** 2015-08-17 10:16 UTC
