### ISSUE TITLE
Profile Links Do Not Display

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#208] opened 2015-07-27 01:45 UTC
Social engine has the ability to include profile fields as links to other members who answer a specific field. Links do not always display even though the structure is there. Custom fields do not display links when  they are set up to do so.

**Comment by shivani2910** [comment] 2015-07-27 11:42
@Elshara It would be great if you could explain this use case using screenshots since we did not exactly understand that which "Links" or section of SocialEngine arfe you referring to. Thanks.

**Comment by Elshara** [comment] 2015-07-27 18:53
Profile links refers to the section of profile questions that can
contain a link to other people who have responded to the question on
their profile.

**Comment by Anshuse** [comment] 2015-08-13 13:43
Hi @Elshara , do you mean that if there's any Profile question/field and when a link posted in this field, then the link is not being displayed as clickable link? Please clarify.

**Comment by Elshara** [comment] 2015-08-13 17:05
Yes that's what I mean.
The link will not display. And if it does display on only certain
questions, the link goes to a dead end.

**Comment by Anshuse** [comment] 2015-08-17 08:44
@Elshara , we're reporting this issue in our internal bug tracker to work on this in near future release. Thanks!

**Comment by Elshara** [comment] 2015-08-17 18:53
Cool!

**Comment by DonnaScriptTechs** [comment] 2017-04-08 10:31
@Elshara I believe there's been a miscommunication. Do you mean:

1. The profile question itself is clickable in the member's profile, which then goes to a page showing all others that answered the question.

or

2. The profile question field allows a URL to be added and the URL is clickable? 

Our team above thought it was the second option but I believe you meant the first option. Please clarify. Thank you.

**Comment by Elshara** [comment] 2017-04-10 22:13
I meant the second.

**Comment by DonnaScriptTechs** [comment] 2017-04-11 13:29
Ok as the first is how you worded it at first. 

> Social engine has the ability to include profile fields as links to other members who answer a specific field. 

I was getting ready to add this bug for that as it doesn't work properly. 

The second is a duplicate of https://github.com/SocialEngine/phpv4-issues/issues/468

I'm keeping this open as a bug since the one I mentioned does not work as it should.

**Comment by Elshara** [comment] 2017-04-11 16:45
I realize this, and know that everyone hates duplicates. Unless they
are merged issues, then everyone hates the fact it's a merged idea.
Thanks for the heads up.

**Comment by DonnaScriptTechs** [comment] 2017-05-15 17:19
This issue was moved to SocialEngine/phpv4-feature-requests#9

**Comment by DonnaScriptTechs** [comment] 2017-05-15 17:20
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.

**Closed by DonnaScriptTechs** 2017-05-15 17:19 UTC
