### ISSUE TITLE
Networks need to be addresed! And add new profile creation options

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#515] opened 2016-11-29 15:29 UTC
This is more a suggestion, to look into.
Mentioned in prev posts, but thought keep in one spot.

Lets be honest Networks option is COMPLETELY USELESS 
Whats the point of Network option, when you can search country's,
I know default networks are like Europe etc and you can make you own.
you can make network for Men, Women, Cat owners, Brandy drinkers etc
And these reflect ONLY 1 SELECTED questions asked.
But if you can simply search these options, then whats the point of Networks?
Like seriously?

In the backend, there should be an option to combine multipul questions/answers to create networks not just 1!
 
example
combining for example the choice of Gender, age, skin type, and location
and selecting the matching answers of for example Men, caucasian, 20-40, in UK
Combine 4 variants to make a specific network called, White Males middle age in UK

Now that is a network!

**Comment by poeticjustice** [comment] 2016-11-29 15:35
Also regards to profile questions
I know there is question and heading.
I think an addition option of description should be added.

You may add a heading to separate the questions, but headings cant have descriptions, so if you wish to add a description to the heading prior to the questions, you have to add like 4 extra headings, as heading supports only a few characters.

plus there should by now, be a tags option, this is like the update thing for sites rather than the outdated multi select.
have multiselect option, but when users click on an answer it removes it from the list and shows the answer as a tag, which can easily be deleted if chose in error, how many times has users accidently released the ctrl key and had to reselect everything again!

**Comment by poeticjustice** [comment] 2016-11-29 15:37
Love to hear all users, developers and social engine teams input here!

**Comment by leandrotavaresrocha** [comment] 2016-11-30 14:01
I use networks in my community since I manage a multilanguage website and in my case networks help me to know how much users from a language I have.

There is a setting in the activity feed where you can setup to display "network and friends", this feature create a common feed to all users that belong to that network, being useful for small communities with a feed with a few entries and avoiding the necessity of people be friends. A users can belong to multiple networks, you just need to setup a multiple answer question.

Products from SEAO (Social Engine Addons) usually have an option to browse based on network, so if you have a multilanguage website with blogs from different languages, your user will see only blogs marked as belonging to network that he selected.

**Comment by poeticjustice** [comment] 2016-11-30 14:37
I can search languages in browse members easily, going to the effort to make networks for each language set up is very long winded process. If it works for you that's great tho.

My point is networks would work better if you can make combinations, 

I started doing networks for profile questions but stopped because I can simply just search them! It made it redundant!

But having networks that you can combine multipul answers makes so much more sense. 

It's almost like taking all data entered and in generates which group you want that member to belong to, which is awesome! 

This seriously needs to be looked into having this feature added, I'm sure it can be done, but no 3rd party developer will edit core codes!

They will all refuse, so it needs to be implemented from the top!

It's simply adding an additional feature to an excisting file

**Comment by leandrotavaresrocha** [comment] 2016-11-30 15:01
The point is that networks are more than just a way to search members. Lets image the following:

User A belong to network English
User B belong to network Spanish
User C belong to network English and Spanish

If you enable the setting that I mentined above each user will see:

User A = Will see content in feed user C
User B = Will see content in feed from C
User C = Will see content in feed from user A and B

There is a small problem in this case, considering that user C can post content in Spanish and English is possible that user A and B see content from a language that they dont know, but this can be solved if the user C take care using the feature to post content only in a specific network according the language.

By default there are just a few features that use networks and until where I know only Social Engine Addons use this feature in its plugins. I am not sure if the possibility to combine answers to create more complex network is a great improvement, at least to me the actual way of work is fine and in a few cases I need a granular control.

Why do you need this detailed use of networks? Maybe is possible to use some type of database analysis than create a more complex network system.

**Comment by poeticjustice** [comment] 2016-12-01 00:48
I have worked on many sites using social engine, and it was always a point raised, even by those who wanted help setting up their network.

some people wanted to combine the answers to create a faction of types of people you could say.

It has also been something that i would love to be looked into for the future

**Comment by Elshara** [comment] 2016-12-07 14:18
Networks should be member categories and people should be able to add their own if they wish.

**Comment by caseynally** [comment] 2016-12-14 06:44
I do not find the Network feature useless, and honestly it is a major part of some of the non-profit sites we run. But I feel it needs to be expanded greatly in options and linking to other features of the site. I wish it could link into view or execution rights on a page or function. I do not agree it should be a "member category" as SE already has different "profile types" and I think the point of the networks is to further define multiple profile types to be grouped by a profile field identifier.... The networks features just needs to be expanded to have more linking "options."

**Comment by Elshara** [comment] 2016-12-14 15:50
Interesting idea you have there. I wonder how that could work.

**Comment by DonnaScriptTechs** [comment] 2017-05-16 09:40
https://github.com/SocialEngine/phpv4-issues/issues/490 duplicate of that one

**Closed by DonnaScriptTechs** 2017-05-16 09:40 UTC
Labels: Enhancement
